import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
const hosting=JSON.parse(readFileSync('.openai/hosting.json','utf8'));
assert.equal(hosting.project_id,'appgprj_6abd87c86b04819183fa71a0a95de282');
assert.equal(hosting.d1,'DB'); assert.equal(hosting.r2,'BUCKET');
const pkg=JSON.parse(readFileSync('package.json','utf8')); assert.equal(pkg.packageManager,'pnpm@11.25.0');
assert.ok(readdirSync('drizzle').includes('0005_flaky_raza.sql'));
const auth=readFileSync('app/api/auth.ts','utf8'); assert.ok(auth.includes('ONYX_OWNER_EMAIL'));
const workflow=readFileSync('.github/workflows/verify.yml','utf8'); for(const s of ['pnpm test','pnpm run lint','pnpm run typecheck','pnpm run build']) assert.ok(workflow.includes(s));
assert.ok(!workflow.includes('deploy')); console.log('Architecture contracts passed');
