import {readFileSync,writeFileSync,mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const root=mkdtempSync(path.join(tmpdir(),'onyx-tests-'));
const files=['lib/domain/model.ts','lib/domain/admin-model.ts','lib/domain/editor-model.ts','lib/domain/advanced-model.ts','lib/domain/form-export.ts','app/api/results/lifecycle/route.ts','app/api/test-forms/publish/route.ts','lib/domain/navigation-model.ts','lib/server/db.ts','lib/server/errors.ts','lib/server/rows.ts','lib/server/results.ts','lib/server/auth.ts','app/api/results/route.ts','app/api/users/route.ts','app/api/forms/route.ts','app/api/test-forms/route.ts','app/api/test-data/route.ts','app/api/evidence/route.ts','app/api/evidence/[id]/route.ts'];
try{
 for(const file of files){let source=readFileSync(file,'utf8');if(file==='lib/domain/model.ts')source=source.replace("import raw from './data/plan.json';",'const raw='+readFileSync('lib/domain/data/plan.json','utf8')+';');source=source.replace(/import\s*\{\s*env\s*\}\s*from\s*['"]cloudflare:workers['"];?/g,'const env=globalThis.__onyxTestEnv;').replaceAll('__ONYX_LOCAL_PREVIEW__','false');let js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;js=js.replace(/from (['"])(\.[^'"]+)\1/g,(_all,q,name)=>'from '+q+name+'.mjs'+q);const target=path.join(root,file.replace(/\.ts$/,'.mjs'));mkdirSync(path.dirname(target),{recursive:true});writeFileSync(target,js);}
 const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0000_pale_solo.sql','utf8'));
 const source=JSON.parse(readFileSync('lib/domain/data/plan.json','utf8'));const first=source.tests[0];
 // Verify deployed legacy rows migrate without losing their saved results.
 sql.prepare('INSERT INTO results VALUES (?,?,?,?,?,?,?,?)').run(first.id,'planned','legacy result','','','',1,'2026-09-01T00:00:00Z');
 sql.exec(readFileSync('drizzle/0001_numerous_blackheart.sql','utf8'));
 for(const migration of (await import('node:fs')).readdirSync('drizzle').filter(f=>/^000[2-9].*\.sql$/.test(f)).sort())sql.exec(readFileSync('drizzle/'+migration,'utf8'));assert.equal(sql.prepare('SELECT actual,custom_values FROM results').get().actual,'legacy result');
 const objects=new Map();globalThis.__onyxTestEnv={ONYX_OWNER_EMAIL:'owner@example.test',DB:{prepare(query){let args=[];const statement=sql.prepare(query);return {bind(...values){args=values;return this;},async first(){return statement.get(...args)??null;},async all(){return {results:statement.all(...args)};},async run(){return statement.run(...args);},execute(){return statement.columns().length?{results:statement.all(...args)}:{results:[],meta:statement.run(...args)};}};},async batch(statements){sql.exec('BEGIN');try{const rows=statements.map(s=>s.execute());sql.exec('COMMIT');return rows;}catch(e){sql.exec('ROLLBACK');throw e;}}},BUCKET:{async put(id,value){objects.set(id,value);},async delete(id){objects.delete(id);},async get(id){return objects.has(id)?{body:objects.get(id)}:null;}}};
 const load=file=>import(pathToFileURL(path.join(root,file.replace(/\.ts$/,'.mjs'))));
 const model=await load('lib/domain/admin-model.ts');const results=await load('app/api/results/route.ts'),users=await load('app/api/users/route.ts'),forms=await load('app/api/forms/route.ts'),data=await load('app/api/test-data/route.ts'),upload=await load('app/api/evidence/route.ts'),download=await load('app/api/evidence/[id]/route.ts');
 const owner={email:'owner@example.test',id:'owner-stable',name:'مالك الاختبار التجريبي'};
 const request=(api,method='GET',body,identity=owner,origin='https://onyx.example.test')=>new Request('https://onyx.example.test/api/'+api,{method,headers:{...(identity?{'oai-authenticated-user-id':identity.id,'oai-authenticated-user-email':identity.email,...(identity.name?{'oai-authenticated-user-full-name':encodeURIComponent(identity.name),'oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'}:{})}:{}),...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const send=(route,api,body,identity=owner)=>route.PUT(request(api,'PUT',body,identity));
 const expect=async(response,status)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
 await expect(await results.GET(request('results','GET',null,null)),401);
 await expect(await results.GET(request('results','GET',null,{email:'unknown@example.test',id:'unknown'})),403);
 const initial=await expect(await results.GET(request('results')),200);assert(initial.user.owner);await expect(await results.GET(request('results','GET',null,{email:owner.email,id:'different-owner-id'})),403);assert.equal(initial.results[first.id].customValues.constructor,Object);
 const user={id:'',email:'viewer@example.test',name:'مشاهد تجريبي',role:'viewer',permissions:model.rolePermissions('viewer'),systems:[first.system],active:true,version:0,updatedAt:''};
 const savedUser=(await expect(await send(users,'users',user),200)).user;assert.equal(savedUser.bound,false);
 await expect(await send(users,'users',user),409);
 const viewer={email:user.email,id:'viewer-stable'};
 assert.equal((await expect(await results.GET(request('results','GET',null,viewer)),200)).user.bound,true);
 const blankResult={id:first.id,status:'planned',actual:'',notes:'',tester:'',evidenceUrl:'',documentNumber:'',linkedDocumentNumber:'',customValues:{},version:1};
 await expect(await send(results,'results',blankResult,viewer),403);
 await expect(await users.GET(request('users','GET',null,viewer)),403);
 await expect(await forms.PUT(request('forms','PUT',{},viewer)),403);
 await expect(await data.PUT(request('test-data','PUT',{},viewer)),403);
 await expect(await upload.POST(request('evidence','POST',{},viewer)),403);
 await expect(await download.GET(request('evidence/x','GET',null,null),{params:Promise.resolve({id:'x'})}),401);
 await expect(await results.PUT(request('results','PUT',blankResult,owner,'https://evil.example')),403);
 await expect(await results.GET(request('results','GET',null,{email:user.email,id:'different-stable-id'})),403);
 const editor=await load('lib/domain/editor-model.ts'),advanced=await load('lib/domain/advanced-model.ts'),testForms=await load('app/api/test-forms/route.ts'),publication=await load('app/api/test-forms/publish/route.ts');
 const fresh=source.tests.find(t=>t.id!==first.id&&t.system===first.system),other=source.tests.find(t=>t.id!==first.id&&t.id!==fresh.id&&t.system===first.system);
 const get=async id=>(await expect(await testForms.GET(request('test-forms?testId='+id)),200)).form;
 const published=async id=>(await expect(await testForms.GET(request('test-forms?mode=published&testId='+id)),200)).form;
 const publish=async f=>expect(await publication.POST(request('test-forms/publish','POST',{testId:f.testId,version:f.version})),200);
 const original=await get(fresh.id);
 const field={id:crypto.randomUUID(),kind:'custom',label:'رقم وثيقة إضافي',type:'code',group:'execution',help:'',placeholder:'',required:false,wide:false,active:true,options:[],defaultValue:'NEW-DEFAULT',min:'',max:'',layout:{desktop:4,tablet:6,mobile:12,rows:3,height:70,gap:4},appearance:{color:'#112233',background:'#ffffff',fontSize:18,radius:9}};
 const bool={...field,id:crypto.randomUUID(),type:'boolean',label:'خيار',defaultValue:true,group:'preparation'},number={...field,id:crypto.randomUUID(),type:'number',label:'رقم',defaultValue:'8',group:'preparation'};
 const conditional={...field,id:crypto.randomUUID(),label:'تفاصيل الفشل',type:'textarea',defaultValue:'',required:true,condition:{fieldId:'execution.status',operator:'eq',value:'failed',action:'show'}};
 const changed={...original,fields:[...original.fields.map(f=>f.id==='execution.documentNumber'?{...f,label:'رقم المستند الفعلي',layout:{desktop:8,tablet:12,mobile:12,rows:3,height:64,gap:0}}:f),field,bool,number,conditional]};
 const draft=(await expect(await send(testForms,'test-forms',changed),200)).form;assert.equal(draft.version,1);assert.equal(draft.fields.find(f=>f.id===field.id).layout.height,70);
 assert(!(await published(fresh.id)).fields.some(f=>f.id===field.id),'draft leaked into execution');
 await expect(await send(testForms,'test-forms',changed),409);
 await expect(await publication.POST(request('test-forms/publish','POST',{testId:fresh.id,version:0})),409);
 await publish(draft);assert.equal((await published(fresh.id)).fields.find(f=>f.id==='execution.documentNumber').label,'رقم المستند الفعلي');
 assert(!(await published(other.id)).fields.some(f=>f.id===field.id),'tests mixed');
 const prepared={...model.emptyTestData(fresh.id),party:'طرف',amount:'0',currency:'YER',ready:true,customValues:{[bool.id]:false,[number.id]:'0'}};
 const preparedSaved=(await expect(await send(data,'test-data',prepared),200)).testData;assert.equal(preparedSaved.customValues[bool.id],false);assert.equal(preparedSaved.customValues[number.id],'0');
 const blank={id:fresh.id,status:'planned',actual:'',notes:'',tester:'اسم مزور',evidenceUrl:'',documentNumber:'0007-A',linkedDocumentNumber:'0001-B',customValues:{[field.id]:''},version:0};
 const recorded=(await expect(await send(results,'results',blank),200)).result;assert.equal(recorded.tester,owner.name);assert.equal(recorded.testerId,owner.id);assert.equal(recorded.customValues[field.id],'');assert.equal(recorded.formSnapshot.version,draft.version);
 const hydrated=editor.hydrateResult(fresh,initial.user,draft,recorded);assert.equal(hydrated.customValues[field.id],'','deliberately empty value replaced');
 const version2=(await expect(await send(testForms,'test-forms',{...draft,fields:draft.fields.filter(f=>f.id!==field.id).map(f=>f.id==='execution.documentNumber'?{...f,label:'عنوان جديد'}:f)}),200)).form;
 await publish(version2);const readback=await expect(await results.GET(request('results')),200);assert(!readback.testForms[fresh.id].fields.some(f=>f.id===field.id));assert(readback.results[fresh.id].formSnapshot.fields.some(f=>f.id===field.id),'historical field lost');assert.equal(readback.results[fresh.id].formSnapshot.fields.find(f=>f.id==='execution.documentNumber').label,'رقم المستند الفعلي');
 await expect(await send(results,'results',{...recorded,status:'failed',actual:'فشل',customValues:{...recorded.customValues,[conditional.id]:''}}),400);
 const failure=(await expect(await send(results,'results',{...recorded,status:'failed',actual:'فشل',customValues:{...recorded.customValues,[conditional.id]:'وصف العطل'}}),200)).result;assert.equal(failure.documentNumber,'0007-A');
 const numeric={...field,id:crypto.randomUUID(),type:'number',label:'الأساس',defaultValue:'',group:'execution'};const calc={...numeric,id:crypto.randomUUID(),type:'calculated',label:'الضريبة',formula:'['+numeric.id+'] * 0.15',precision:2};
 const otherForm=await get(other.id);const formulaDraft=(await expect(await send(testForms,'test-forms',{...otherForm,fields:[...otherForm.fields,numeric,calc]}),200)).form;await publish(formulaDraft);
 const computed=(await expect(await send(results,'results',{...blank,id:other.id,customValues:{[numeric.id]:'100',[calc.id]:'999999'}}),200)).result;assert.equal(computed.customValues[calc.id],'15.00');
 assert.throws(()=>advanced.calculate('1/0',{}));assert.throws(()=>advanced.calculate('process.exit()',{}));assert.equal(advanced.calculate('(2+3)*4',{}),'20');
 await expect(await send(testForms,'test-forms',{...formulaDraft,fields:formulaDraft.fields.map(f=>f.id===numeric.id?{...f,type:'textarea'}:f)}),400);
 await expect(await send(testForms,'test-forms',{...formulaDraft,fields:formulaDraft.fields.map(f=>f.id===numeric.id?{...f,condition:{fieldId:calc.id,operator:'filled',value:'',action:'show'}}:f)}),400);
 await expect(await send(testForms,'test-forms',{...formulaDraft,fields:formulaDraft.fields.filter(f=>f.id!==numeric.id)}),400);
 const duser=(await expect(await send(users,'users',{...user,id:'',email:'designer@example.test',role:'designer',name:'مصمم',permissions:model.rolePermissions('designer')}),200)).user;
 const designer={email:duser.email,id:'designer-stable'};await expect(await publication.POST(request('test-forms/publish','POST',{testId:other.id,version:formulaDraft.version},designer)),403);
 await expect(await testForms.GET(request('test-forms?testId='+fresh.id,'GET',null,viewer)),403);await expect(await testForms.GET(request('test-forms?mode=published&testId='+fresh.id,'GET',null,viewer)),200);
 await expect(await send(testForms,'test-forms',version2,viewer),403);
 const priorConsole=console.error;sql.exec("CREATE TRIGGER fail_history BEFORE INSERT ON test_form_versions BEGIN SELECT RAISE(ABORT, 'audit failure'); END;");console.error=()=>{};try{await expect(await send(testForms,'test-forms',{...version2,fields:version2.fields.map(f=>({...f,label:f.label+'!'}))}),503);}finally{console.error=priorConsole;sql.exec('DROP TRIGGER fail_history');}
 assert.equal((await get(fresh.id)).version,version2.version,'partial transaction committed');
 const navigation=await load('lib/domain/navigation-model.ts');assert.deepEqual(navigation.readWorkspaceLocation(navigation.writeWorkspaceLocation({view:'builder',testId:fresh.id,execute:true}),[fresh.id]),{view:'builder',testId:fresh.id,execute:true});
 assert.equal(editor.hydrateData(fresh.id,draft,preparedSaved).customValues[bool.id],false);assert.equal(editor.hydrateData(fresh.id,draft,preparedSaved).customValues[number.id],'0');
 assert.equal(sql.prepare('SELECT actual FROM results WHERE id=?').get(first.id).actual,'legacy result');assert(sql.prepare('SELECT form_snapshot FROM results WHERE id=?').get(first.id).form_snapshot);
 console.log('PASS: migration retains legacy data and frozen definitions; draft/publication separation; revision conflict and atomic rollback; server permissions; original field layout and label readback; independent tests; historical deleted fields; zero/false/empty preservation; conditional validation; safe formulas recomputed on server; incompatible type changes rejected; authenticated tester; document codes retain leading zeroes.');
 const lifecycle=await load('app/api/results/lifecycle/route.ts');
 const approval=(await expect(await lifecycle.POST(request('results/lifecycle','POST',{testId:fresh.id,version:failure.version,action:'approve'})),200)).result;assert(approval.approvedAt);
 await expect(await send(results,'results',{...approval,actual:'تغيير بعد الاعتماد'}),400);
 const newRun=(await expect(await lifecycle.POST(request('results/lifecycle','POST',{testId:fresh.id,version:approval.version,action:'new'})),200)).result;assert.equal(newRun.status,'planned');assert.equal(newRun.formSnapshot.version,version2.version);assert(newRun.runId);assert.equal(newRun.approvedAt,'');
 const histories=(await expect(await lifecycle.GET(request('results/lifecycle?testId='+fresh.id)),200)).history;assert.equal(histories.length,1);assert.equal(histories[0].snapshot.actual,'فشل');assert.equal(histories[0].snapshot.formSnapshot.version,draft.version);
 await expect(await lifecycle.POST(request('results/lifecycle','POST',{testId:fresh.id,version:approval.version,action:'new'})),409);assert.equal((await expect(await lifecycle.GET(request('results/lifecycle?testId='+fresh.id)),200)).history.length,1);
 const exports=await load('lib/domain/form-export.ts');for(const format of ['docx','xlsx'])writeFileSync('/tmp/onyx-export-test.'+format,exports.createFormExport(draft,'execution',editor.resultValues(failure,failure.tester),format));
 console.log('PASS: approved results immutable; new runs archive prior definitions and answers; conflicts do not duplicate history; DOCX/XLSX generated with dynamic values.');
 sql.close();
}finally{rmSync(root,{recursive:true,force:true});delete globalThis.__onyxTestEnv;}
