"use client";
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Choice,Tick,newFieldId} from './form-fields';
import type {FormField,TestForm} from '../lib/domain/editor-model';
export function AdvancedProperties({field:f,form,patch}:{field:FormField;form:TestForm;patch:(v:Partial<FormField>)=>void}){
 const layout=f.layout??{desktop:f.wide?12:6,tablet:f.wide?12:6,mobile:12,rows:3,height:0,gap:0};const appearance=f.appearance??{color:'#183e30',background:'#ffffff',fontSize:16,radius:6};
 return <div className="settings-fields advanced-properties"><details open><summary>الحجم والتخطيط</summary><div className="settings-fields"><div className="form-row">{(['desktop','tablet','mobile'] as const).map((k,i)=><label key={k}>{['أعمدة الحاسوب','أعمدة الجهاز اللوحي','أعمدة الهاتف'][i]}<Input aria-label={['عرض الحاسوب','عرض الجهاز اللوحي','عرض الهاتف'][i]} type="number" min="1" max="12" value={layout[k]} onChange={e=>patch({layout:{...layout,[k]:Number(e.target.value)}})}/></label>)}<label>الارتفاع بالبكسل — صفر للتلقائي<Input type="number" min="0" max="1000" value={layout.height} onChange={e=>patch({layout:{...layout,height:Number(e.target.value)}})}/></label><label>عدد أسطر النص<Input type="number" min="1" max="30" value={layout.rows} onChange={e=>patch({layout:{...layout,rows:Number(e.target.value)}})}/></label><label>المسافة الداخلية<Input type="number" min="0" max="80" value={layout.gap} onChange={e=>patch({layout:{...layout,gap:Number(e.target.value)}})}/></label></div><label>اسم القسم أو المجموعة<Input value={f.section??''} maxLength={120} onChange={e=>patch({section:e.target.value})}/></label></div></details>
 <details><summary>المظهر والسلوك</summary><div className="settings-fields"><div className="form-row"><label>لون النص<Input type="color" value={appearance.color} onChange={e=>patch({appearance:{...appearance,color:e.target.value}})}/></label><label>لون مساحة الإدخال<Input type="color" value={appearance.background} onChange={e=>patch({appearance:{...appearance,background:e.target.value}})}/></label><label>حجم الخط<Input type="number" min="14" max="36" value={appearance.fontSize} onChange={e=>patch({appearance:{...appearance,fontSize:Number(e.target.value)}})}/></label><label>استدارة الحدود<Input type="number" min="0" max="40" value={appearance.radius} onChange={e=>patch({appearance:{...appearance,radius:Number(e.target.value)}})}/></label></div><Tick checked={!!f.readOnly} onChange={v=>patch({readOnly:v})}>للقراءة فقط</Tick><Tick checked={!!f.disabled} onChange={v=>patch({disabled:v})}>تعطيل الإدخال</Tick><Tick checked={f.printVisible!==false} onChange={v=>patch({printVisible:v})}>إظهار في الطباعة</Tick></div></details>
 {f.group==='execution'&&!['status','file','user'].includes(f.type)&&<label>مصدر القيمة من التهيئة<Choice label="مصدر التهيئة" value={f.preparationSource??'none'} options={[["none","القيمة الافتراضية فقط"],...form.fields.filter(x=>x.group==='preparation'&&x.key!=='ready'&&!['heading','note','section','space','separator'].includes(x.type)).map(x=>[x.id,x.label] as [string,string])]} onChange={v=>patch({preparationSource:v==='none'?undefined:v})}/></label>}
 <details><summary>شرط مرئي</summary><div className="settings-fields"><label>الحقل الذي يعتمد عليه الشرط<Choice label="حقل الشرط" value={f.condition?.fieldId??'none'} options={[["none","بدون شرط"],...form.fields.filter(x=>x.id!==f.id&&!['content','heading','note','file','section','separator','space'].includes(x.type)).map(x=>[x.id,x.label] as [string,string])]} onChange={v=>patch({condition:v==='none'?undefined:{fieldId:v,operator:'eq',value:'',action:'show'}})}/></label>{f.condition&&<><label>المقارنة<Choice label="مقارنة الشرط" value={f.condition.operator} options={[["eq","يساوي"],["ne","لا يساوي"],["gt","أكبر من"],["lt","أقل من"],["filled","لديه قيمة"]]} onChange={v=>patch({condition:{...f.condition!,operator:v as NonNullable<FormField['condition']>['operator']}})}/></label><label>القيمة<Input value={f.condition.value} maxLength={300} onChange={e=>patch({condition:{...f.condition!,value:e.target.value}})}/></label><label>عند تحقق الشرط<Choice label="إجراء الشرط" value={f.condition.action} options={[["show","إظهار الحقل؛ يُخفى عند عدم التحقق"],["require","جعل الحقل مطلوباً"],["disable","تعطيل الحقل"]]} onChange={v=>patch({condition:{...f.condition!,action:v as NonNullable<FormField['condition']>['action']}})}/></label><p className="muted">تُحفظ قيم الحقول المخفية، ولا تُفرض إلزاميتها أثناء إخفائها.</p></>}</div></details>
 {f.type==='calculated'&&<details open><summary>المعادلة والدقة</summary><label>المعادلة<Textarea dir="ltr" value={f.formula??''} onChange={e=>patch({formula:e.target.value})} placeholder="[معرّف الحقل] * 0.15"/></label><label>إضافة مرجع حقل<Choice label="مرجع المعادلة" value="none" options={[["none","اختر حقلاً لإضافته"],...form.fields.filter(x=>x.id!==f.id&&['number','amount','integer','percent','calculated','duration'].includes(x.type)).map(x=>[x.id,x.label] as [string,string])]} onChange={v=>v!=='none'&&patch({formula:(f.formula??'')+'['+v+']'})}/></label><label>المنازل العشرية<Input type="number" min="0" max="8" value={f.precision??2} onChange={e=>patch({precision:Number(e.target.value)})}/></label><p className="muted">العمليات المدعومة: + − × ÷ والأقواس. القيم الناقصة تبقى فارغة والقسمة على صفر تظهر خطأ.</p></details>}
 {f.type==='table'&&<details open><summary>أعمدة الجدول</summary><div className="settings-fields">{(f.columns??[]).map((c,i)=><div key={c.id} className="settings-fields"><Input aria-label={'عنوان العمود '+(i+1)} value={c.label} onChange={e=>patch({columns:f.columns!.map(x=>x.id===c.id?{...x,label:e.target.value}:x)})}/><Choice label={'نوع العمود '+(i+1)} value={c.type} options={[["text","نص"],["number","عدد"],["date","تاريخ"],["boolean","اختيار"]]} onChange={v=>patch({columns:f.columns!.map(x=>x.id===c.id?{...x,type:v as NonNullable<FormField['columns']>[number]['type']}:x)})}/><label>عرض العمود<Input type="number" min="60" max="600" value={c.width} onChange={e=>patch({columns:f.columns!.map(x=>x.id===c.id?{...x,width:Number(e.target.value)}:x)})}/></label><Tick checked={c.required} onChange={v=>patch({columns:f.columns!.map(x=>x.id===c.id?{...x,required:v}:x)})}>مطلوب</Tick><div className="action-cluster"><Button type="button" variant="outline" size="sm" disabled={!i} onClick={()=>{const a=[...f.columns!];[a[i-1],a[i]]=[a[i],a[i-1]];patch({columns:a});}}>أعلى</Button><Button type="button" variant="outline" size="sm" onClick={()=>patch({columns:f.columns!.filter(x=>x.id!==c.id)})}>حذف العمود</Button></div></div>)}<Button type="button" variant="outline" onClick={()=>patch({columns:[...(f.columns??[]),{id:newFieldId(),label:'عمود جديد',type:'text',required:false,width:160}]})}>إضافة عمود</Button></div></details>}
 {['select','radio','searchselect','multiselect'].includes(f.type)&&<details><summary>أسماء الخيارات وحالتها</summary><div className="settings-fields">{f.options.map(o=>{const item=f.optionItems?.find(x=>x.value===o)??{value:o,label:o,disabled:false};function set(p:Partial<typeof item>){patch({optionItems:[...(f.optionItems??[]).filter(x=>x.value!==o),{...item,...p}]});}return <div key={o}><small dir="ltr">{o}</small><Input aria-label={'الاسم الظاهر '+o} value={item.label} onChange={e=>set({label:e.target.value})}/><Tick checked={item.disabled} onChange={v=>set({disabled:v})}>تعطيل الخيار للتنفيذات الجديدة</Tick></div>;})}</div></details>}
 <small dir="ltr">{f.id}</small></div>;
}
