"use client";
import {downloadForm} from "./form-export";
import {useEffect,useState} from 'react';
import {SlidersHorizontal,Save,Plus,Eye,EyeOff,ArrowUp,ArrowDown,Copy,Undo2,Redo2,History,RotateCcw,Play,Database,GripVertical} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {states,type Screen,type TestCase} from './model';
import {AdvancedProperties} from './advanced-properties';
import {can,type AppUser,type Values} from './admin-model';
import {baseFields,groupLabels,editorTypes,allowedTypes,isLockedVisible,isReadOnlyValue,validateTestForm,rebasePreview,restoreRevision,initialResult,initialData,resultValues,dataValues,type FormGroup,type FormField,type TestForm,type FormRevision} from './editor-model';
import {Choice,Tick,newFieldId,readResponse} from './form-fields';
import {ConfiguredFields} from './configured-fields';
import {TestPicker} from './test-preparation';
export function FormBuilder({screens,test,user,initial,onSelect,onSave,onDirty,onExecute,onPrepare}:{screens:Screen[];test:TestCase;user:AppUser;initial:TestForm;onSelect:(id:string)=>void;onSave:(v:TestForm)=>Promise<TestForm>;onDirty:(v:boolean)=>void;onExecute:()=>void;onPrepare:()=>void}){
 const [device,setDevice]=useState('desktop'),[paletteQuery,setPaletteQuery]=useState(''),[bulk,setBulk]=useState<string[]>([]),[autosave,setAutosave]=useState(false);
 const [form,setForm]=useState(initial),[group,setGroup]=useState<FormGroup>('execution'),[selected,setSelected]=useState('execution.status'),[past,setPast]=useState<TestForm[]>([]),[future,setFuture]=useState<TestForm[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[previewGroup,setPreviewGroup]=useState<'execution'|'preparation'>('execution'),[previewValues,setPreviewValues]=useState<Values>({}),[historyOpen,setHistoryOpen]=useState(false),[revisions,setRevisions]=useState<FormRevision[]>([]),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState('');
 const modified=JSON.stringify(form.fields)!==JSON.stringify(initial.fields);const field=form.fields.find(f=>f.id===selected);const visible=form.fields.filter(f=>f.group===group),listed=visible.filter(f=>f.label.includes(query)||editorTypes[f.type].includes(query));
 useEffect(()=>{setForm(initial);setPast([]);setFuture([]);setError('');setPreviewValues({});onDirty(false);},[initial]);
 function adopt(next:TestForm){setPreviewValues(p=>rebasePreview(p,form,next));setPast(p=>[...p,form].slice(-60));setFuture([]);setForm(next);setError('');onDirty(JSON.stringify(next.fields)!==JSON.stringify(initial.fields));}
 function patch(p:Partial<FormField>){if(!field)return;adopt({...form,fields:form.fields.map(f=>f.id===selected?{...f,...p}:f)});}
 function undo(){const next=past.at(-1);if(!next)return;setPreviewValues(p=>rebasePreview(p,form,next));setPast(p=>p.slice(0,-1));setFuture(p=>[form,...p]);setForm(next);setError('');onDirty(JSON.stringify(next.fields)!==JSON.stringify(initial.fields));}
 function redo(){const next=future[0];if(!next)return;setPreviewValues(p=>rebasePreview(p,form,next));setPast(p=>[...p,form]);setFuture(p=>p.slice(1));setForm(next);setError('');onDirty(JSON.stringify(next.fields)!==JSON.stringify(initial.fields));}
 function add(copy?:FormField,chosenType?:FormField['type']){const f:FormField=copy?{...copy,id:newFieldId(),kind:'custom',key:undefined,label:copy.label+' — نسخة'}:{id:newFieldId(),kind:'custom',label:'حقل جديد',type:chosenType??(group==='instructions'?'note':'text'),group,help:'',placeholder:'',required:false,wide:group==='instructions',active:true,options:[],defaultValue:'',min:'',max:''};if(f.type==='consent')f.defaultValue=false;if(f.type==='table')f.columns=[{id:newFieldId(),label:'الإجراء',type:'text',required:false,width:220},{id:newFieldId(),label:'النتيجة',type:'text',required:false,width:220}];adopt({...form,fields:[...form.fields,f]});setSelected(f.id);setQuery('');}
 function move(id:string,target:string){if(id===target)return;const from=form.fields.find(f=>f.id===id),to=form.fields.find(f=>f.id===target);if(!from||!to||from.group!==to.group)return;const positions=form.fields.flatMap((f,i)=>f.group===from.group?[i]:[]),items=positions.map(i=>form.fields[i]);const old=items.findIndex(f=>f.id===id),at=items.findIndex(f=>f.id===target);items.splice(old,1);items.splice(at,0,from);const next=[...form.fields];positions.forEach((p,i)=>next[p]=items[i]);adopt({...form,fields:next});}
 async function save(silent=false){setBusy(true);setError('');try{const saved=await onSave(validateTestForm(form));setForm(saved);setPast([]);setFuture([]);onDirty(false);if(!silent)toast.success('حُفظت المسودة. انشر النموذج لإتاحته للتنفيذات الجديدة.');}catch(e){setError((e as Error).message);setAutosave(false);}finally{setBusy(false);}}
 async function history(){setHistoryOpen(true);setHistoryBusy(true);setHistoryError('');try{const d=await readResponse(await fetch('/api/test-forms?testId='+encodeURIComponent(test.id),{cache:'no-store'}));setRevisions(d.revisions);}catch(e){setHistoryError((e as Error).message);}finally{setHistoryBusy(false);}}
 useEffect(()=>{if(!autosave||!modified||busy)return;const timer=setTimeout(()=>void save(true),1800);return()=>clearTimeout(timer);},[form,autosave,modified,busy]);
 async function publish(){setBusy(true);setError('');try{const d=await readResponse(await fetch('/api/test-forms/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({testId:form.testId,version:form.version})}));setForm(d.form);toast.success('نُشر الإصدار '+d.form.version+' للتنفيذات الجديدة.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function remove(ids:string[]){if(ids.some(id=>{const f=form.fields.find(x=>x.id===id);return f&&isLockedVisible(f);})){setError('الحالة والنتيجة الفعلية والجاهزية عناصر مطلوبة للنظام.');return;}if(!window.confirm('حذف '+ids.length+' عنصر من الإصدار الجديد؟ تبقى السجلات السابقة محفوظة.'))return;adopt({...form,fields:form.fields.filter(f=>!ids.includes(f.id))});setBulk([]);}
 const preview={...resultValues(initialResult(test,user,form),user.name),...dataValues(initialData(test.id,form)),...previewValues};
 return <section className="plan-surface admin-surface full-builder"><div className="section-heading"><div><h2><SlidersHorizontal size={22}/>محرر نماذج الاختبارات</h2><p>حرّر جميع الحقول ومحتوى الاختبار، ثم احفظ المسودة وانشر إصداراً لهذا الاختبار.</p></div><Button variant="outline" onClick={()=>void history()}><History size={16}/>سجل الإصدارات</Button></div>
 <TestPicker screens={screens} test={test} onSelect={onSelect} prefix="المحرر"/>
 <div className="context-banner"><div><b>{test.screen}</b><p>{test.scenario} <code>{test.id}</code></p></div><span className="data-status">{initial.version?'إصدار النموذج '+initial.version:initial.origin==='screen'?'حقول الشاشة السابقة محفوظة':'النموذج الأساسي'}</span></div>
 <div className="definition-actions"><span className="publish-state">النطاق: هذا الاختبار فقط · مسودة</span><Tick checked={autosave} onChange={setAutosave}>حفظ تلقائي للمسودة</Tick><Button variant="outline" onClick={()=>downloadForm(form,previewGroup,preview,'docx')}>تصدير DOCX</Button><Button variant="outline" onClick={()=>downloadForm(form,previewGroup,preview,'xlsx')}>تصدير XLSX</Button><Button variant="outline" onClick={()=>window.print()}>طباعة A4</Button><Button variant="outline" onClick={()=>{const blob=new Blob([JSON.stringify({schemaVersion:1,fields:form.fields},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='onyx-form-'+test.id+'.json';a.click();URL.revokeObjectURL(a.href);}}>تصدير قالب JSON</Button><label>استيراد نسخة مستقلة<Input type="file" accept=".json" disabled={busy} onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024)throw new Error('حجم القالب يتجاوز ١ ميجابايت.');const d=JSON.parse(await file.text());if(d.schemaVersion!==1||!Array.isArray(d.fields))throw new Error('صيغة القالب غير صحيحة.');const ids=new Map<string,string>(d.fields.filter((f:FormField)=>f.kind==='custom').map((f:FormField)=>[f.id,newFieldId()]));const fields=d.fields.map((f:FormField)=>({...f,id:ids.get(f.id)??f.id,condition:f.condition?{...f.condition,fieldId:ids.get(f.condition.fieldId)??f.condition.fieldId}:undefined,formula:f.formula?.replace(/\[([^\]]+)\]/g,(_:string,id:string)=>'['+(ids.get(id)??id)+']')}));const next=validateTestForm({...form,fields});if(window.confirm('استيراد '+fields.length+' عنصر كمسودة لهذا الاختبار؟ لن تتغير النتائج السابقة.'))adopt(next);}catch(err){setError((err as Error).message);}finally{e.target.value='';}}}/></label></div><div className="builder-toolbar"><Tabs dir="rtl" value={group} onValueChange={v=>{setGroup(v as FormGroup);setSelected(form.fields.find(f=>f.group===v)?.id??'');setQuery('');if(v!=='instructions')setPreviewGroup(v as 'execution'|'preparation');}}><TabsList>{Object.entries(groupLabels).map(([key,label])=><TabsTrigger key={key} value={key}>{label} <small>{form.fields.filter(f=>f.group===key&&f.active).length}</small></TabsTrigger>)}</TabsList></Tabs><div className="action-cluster"><Button variant="outline" size="sm" onClick={undo} disabled={!past.length||busy} aria-label="تراجع عن التعديل"><Undo2 size={16}/></Button><Button variant="outline" size="sm" onClick={redo} disabled={!future.length||busy} aria-label="إعادة التعديل"><Redo2 size={16}/></Button><Button onClick={()=>add()} disabled={busy||form.fields.filter(f=>f.kind==='custom').length>=100}><Plus size={16}/>إضافة حقل</Button></div></div>
 <div className="complete-builder"><aside className="field-library"><h3>مكتبة العناصر</h3><Input placeholder="ابحث عن نوع عنصر…" aria-label="البحث في مكتبة العناصر" value={paletteQuery} onChange={e=>setPaletteQuery(e.target.value)}/><div className="element-palette">{Object.entries(editorTypes).filter(([k,v])=>!['content','status','user','file'].includes(k)&&v.includes(paletteQuery)&&(group!=='instructions'||['heading','note','alert','section','separator','space'].includes(k))).map(([k,v])=><button type="button" key={k} disabled={busy} onClick={()=>add(undefined,k as FormField['type'])}>{v}</button>)}</div>{baseFields(test).filter(f=>f.group===group&&!form.fields.some(x=>x.id===f.id)).map(f=><Button variant="outline" size="sm" key={f.id} onClick={()=>{adopt({...form,fields:[...form.fields,f]});setSelected(f.id);}}>استعادة {f.label}</Button>)}<h3>عناصر النموذج</h3><Input aria-label="البحث عن حقل" placeholder="ابحث عن حقل…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted">{visible.length} حقلاً · {visible.filter(f=>!f.active).length} مخفياً</p><div className="action-cluster"><Button variant="outline" size="sm" onClick={()=>setBulk(visible.map(f=>f.id))}>تحديد الكل</Button><Button variant="outline" size="sm" disabled={!bulk.length||busy} onClick={()=>{adopt({...form,fields:form.fields.map(f=>bulk.includes(f.id)&&!isLockedVisible(f)?{...f,active:false}:f)});setBulk([]);}}>إخفاء المحدد</Button><Button variant="outline" size="sm" disabled={!bulk.length||busy} onClick={()=>remove(bulk)}>حذف المحدد</Button></div><div className="field-list">{listed.map(f=><div key={f.id}><Tick checked={bulk.includes(f.id)} onChange={v=>setBulk(p=>v?[...p,f.id]:p.filter(x=>x!==f.id))}>تحديد {f.label}</Tick><button type="button" key={f.id} draggable={!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',f.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'),f.id);}} onClick={()=>setSelected(f.id)} className={'field-choice '+(selected===f.id?'selected ':'')+(!f.active?'hidden-field':'')}><GripVertical size={15}/><div><b>{f.label}</b><small>{editorTypes[f.type]} · {f.kind==='builtin'?'أساسي':'مخصص'}{f.required?' · مطلوب':''}</small></div>{f.active?<Eye size={15}/>:<EyeOff size={15}/>}</button></div>)}</div>{!listed.length&&<p className="muted">لا يوجد حقل يطابق البحث.</p>}</aside>
 <section className="field-settings">{field&&field.group===group?<><div className="settings-heading"><h3>إعدادات الحقل</h3><span className="field-kind">{field.kind==='builtin'?'حقل أساسي':'حقل مخصص'}</span></div><fieldset disabled={busy} className="settings-fields"><label>عنوان الحقل<Input aria-label="عنوان الحقل" value={field.label} onChange={e=>patch({label:e.target.value})} maxLength={120}/></label><label>نوع الحقل<Choice label="نوع الحقل" value={field.type} options={allowedTypes(field)} onChange={v=>patch({type:v as FormField['type'],defaultValue:['boolean','consent'].includes(v)?false:['boolean','consent'].includes(field.type)?'':field.defaultValue})}/></label>
 {field.kind==='custom'&&<label>موضع الحقل<Choice label="موضع الحقل" value={field.group} options={Object.entries(groupLabels)} onChange={v=>{patch({group:v as FormGroup,...(v==='instructions'?{type:'note',required:false,wide:true}:field.group==='instructions'?{type:'text',defaultValue:''}:{})});setGroup(v as FormGroup);if(v!=='instructions')setPreviewGroup(v as 'execution'|'preparation');}}/></label>}
 <label>تعليمات الحقل<Textarea aria-label="تعليمات الحقل" value={field.help} onChange={e=>patch({help:e.target.value})} maxLength={1000} rows={2}/></label>
 {!['content','heading','note','user','file','status','boolean'].includes(field.type)&&<label>النص التوضيحي<Input aria-label="النص التوضيحي" value={field.placeholder} onChange={e=>patch({placeholder:e.target.value})} maxLength={300}/></label>}
 {['select','radio','searchselect','multiselect'].includes(field.type)&&<label>خيارات القائمة — خيار في كل سطر<Textarea aria-label="خيارات القائمة" value={field.options.join('\n')} onChange={e=>patch({options:e.target.value.split('\n')})} rows={4}/></label>}
 {['content','note'].includes(field.type)?<label>{field.type==='content'?'محتوى الاختبار':'محتوى الملاحظة'}<Textarea aria-label={field.type==='content'?'محتوى الاختبار':'محتوى الملاحظة'} value={String(field.defaultValue)} onChange={e=>patch({defaultValue:e.target.value})} rows={6} maxLength={10000} disabled={isReadOnlyValue(field)}/></label>:!['heading','note','user','file'].includes(field.type)&&<label>القيمة الافتراضية{['boolean','consent'].includes(field.type)?<Tick checked={field.defaultValue===true} onChange={v=>patch({defaultValue:v})}>محدد افتراضياً</Tick>:field.type==='status'?<Choice label="الحالة الافتراضية" value={String(field.defaultValue)} options={Object.entries(states)} onChange={v=>patch({defaultValue:v})}/>:<Input aria-label="القيمة الافتراضية" value={String(field.defaultValue)} onChange={e=>patch({defaultValue:e.target.value})} type={field.type==='date'?'date':field.type==='url'?'url':['number','amount'].includes(field.type)?'number':'text'} step="any" maxLength={10000}/>}</label>}
 {!['content','heading','note','user','file'].includes(field.type)&&<p className="muted">تظهر القيمة الافتراضية عند إنشاء بيانات جديدة. لاستبدال قيمة محفوظة، افتح التهيئة أو التنفيذ واستخدم «تطبيق قيم النموذج» ثم احفظ.</p>}
 {['number','amount'].includes(field.type)&&<div className="form-row"><label>الحد الأدنى<Input aria-label="الحد الأدنى" type="number" step="any" value={field.min} onChange={e=>patch({min:e.target.value})}/></label><label>الحد الأعلى<Input aria-label="الحد الأعلى" type="number" step="any" value={field.max} onChange={e=>patch({max:e.target.value})}/></label></div>}
 {isReadOnlyValue(field)&&<p className="access-note">{field.type==='user'?'قيمة هذا الحقل هي المستخدم المسجل دخوله، وتُثبت تلقائياً عند الحفظ.':field.type==='file'?'الملفات تُضاف أثناء التنفيذ، ويمكنك تحرير عنوان الحقل وتعليماته وإلزاميته وظهوره.':'مرجع المصدر ثابت. يمكنك تحرير عنوانه وتعليماته وظهوره.'}</p>}
 <AdvancedProperties field={field} form={form} patch={patch}/><Button variant="outline" onClick={()=>remove([field.id])} disabled={isLockedVisible(field)}>حذف من الإصدار الجديد</Button><div className="field-flags"><Tick checked={field.active} onChange={v=>patch({active:v})} disabled={isLockedVisible(field)}>إظهار الحقل في النموذج</Tick><Tick checked={field.wide} onChange={v=>patch({wide:v})}>عرض السطر كاملاً</Tick>{!['content','heading','note','status','user'].includes(field.type)&&<Tick checked={field.required} onChange={v=>patch({required:v})} disabled={field.id==='execution.actual'}>حقل مطلوب عند الحسم أو إعلان الجاهزية</Tick>}</div>
 <div className="action-cluster"><Button variant="outline" size="sm" onClick={()=>move(field.id,visible[visible.findIndex(f=>f.id===field.id)-1]?.id)} disabled={visible[0]?.id===field.id}><ArrowUp size={15}/>أعلى</Button><Button variant="outline" size="sm" onClick={()=>move(field.id,visible[visible.findIndex(f=>f.id===field.id)+1]?.id)} disabled={visible.at(-1)?.id===field.id}><ArrowDown size={15}/>أسفل</Button>{field.kind==='custom'?<Button size="sm" variant="outline" onClick={()=>add(field)}><Copy size={15}/>نسخ الحقل</Button>:<Button size="sm" variant="outline" onClick={()=>patch(baseFields(test).find(f=>f.id===field.id)!)}><RotateCcw size={15}/>استعادة الأصل</Button>}</div></fieldset></>:<p>اختر حقلاً لتحرير إعداداته.</p>}</section>
 <section className={'form-preview preview-'+device}><div className="settings-heading"><h3><Eye size={17}/>معاينة النموذج</h3><span>تجريبية</span></div><Tabs dir="rtl" value={previewGroup} onValueChange={v=>setPreviewGroup(v as 'execution'|'preparation')}><TabsList><TabsTrigger value="execution">التنفيذ</TabsTrigger><TabsTrigger value="preparation">التهيئة</TabsTrigger></TabsList></Tabs><div className="builder-device-tools">{[['desktop','حاسوب'],['tablet','جهاز لوحي'],['mobile','هاتف']].map(([k,v])=><Button variant={device===k?'default':'outline'} size="sm" key={k} onClick={()=>setDevice(k)}>{v}</Button>)}</div><div className="preview-scroll"><ConfiguredFields form={form} group="instructions" values={{}} onChange={()=>{}} preview selected={selected} onSelect={setSelected}/><ConfiguredFields form={form} group={previewGroup} values={preview} onChange={(f,v)=>setPreviewValues(p=>({...p,[f.id]:v}))} preview selected={selected} onSelect={setSelected}/></div><p className="muted">المعاينة لا تحفظ نتائج أو بيانات اختبار.</p></section></div>
 {error&&<p role="alert" className="form-error">{error}</p>}<div className="builder-footer"><div className="save-row"><Button onClick={()=>void save()} disabled={busy||!modified&&initial.version>0}><Save size={17}/>{busy?'جارٍ الحفظ…':'حفظ المسودة'}</Button>{can(user,'publish',test.system)&&<Button onClick={()=>void publish()} disabled={busy||modified||!form.version}>نشر الإصدار</Button>}<span role="status">{modified?'تعديلات لم تُحفظ':initial.version===0&&initial.origin==='screen'?'إعدادات الشاشة السابقة · احفظ لتخصيص الاختبار':initial.updatedAt?'محفوظ · '+new Date(initial.updatedAt).toLocaleString('ar-YE',{timeZone:'Asia/Aden'}):'احفظ النموذج بعد التخصيص'}</span></div><div className="action-cluster"><Button variant="outline" onClick={onExecute}><Play size={16}/>فتح التنفيذ</Button><Button variant="outline" onClick={onPrepare}><Database size={16}/>فتح التهيئة</Button></div></div>
 <Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent dir="rtl" className="form-history"><DialogHeader><DialogTitle>إصدارات نموذج الاختبار</DialogTitle><DialogDescription>{test.scenario} · {test.id} — أحدث ٢٠ إصداراً محفوظاً. استعادة الإصدار تضعه في المحرر لمراجعته ثم حفظه.</DialogDescription></DialogHeader>{historyBusy?<p role="status">جارٍ تحميل الإصدارات…</p>:historyError?<p role="alert" className="form-error">{historyError}</p>:revisions.length?<div className="revision-list">{revisions.map(r=><div className="revision-row" key={r.version}><div><b>الإصدار {r.version}</b><p>{r.actorName} · {new Date(r.createdAt).toLocaleString('ar-YE',{timeZone:'Asia/Aden'})}</p><small>{r.snapshot.fields.filter(f=>f.active).length} حقلاً ظاهراً</small></div><Button variant="outline" size="sm" onClick={()=>{adopt(restoreRevision(r.snapshot,form));setHistoryOpen(false);toast.info('حُمّل الإصدار للمراجعة. احفظ النموذج لتطبيقه.');}}>استعادة للمراجعة</Button></div>)}</div>:<p>لا توجد إصدارات مخصصة محفوظة لهذا الاختبار بعد.</p>}</DialogContent></Dialog>
 </section>;
}