"use client";
import {downloadForm} from "../lib/domain/form-export";
import {useEffect,useState} from 'react';
import {Database,Save,CheckCheck,Play,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
import {plan,type Screen,type TestCase} from '../lib/domain/model';
import type {TestData,FieldValue} from '../lib/domain/admin-model';
import {hydrateData,applyDefaultChanges,dataValues,validateConfiguredData,preparationIssue,type FormField,type TestForm} from '../lib/domain/editor-model';
import {Choice} from './form-fields';
import {Input} from '@/components/ui/input';
import {ApplyFormDefaults,FormVersion} from './apply-form-defaults';
import {ConfiguredFields} from './configured-fields';
export function TestPicker({screens,test,onSelect,prefix}:{screens:Screen[];test:TestCase;onSelect:(id:string)=>void;prefix:string}){const [search,setSearch]=useState('');const ids=new Set(screens.flatMap(s=>s.testIds)),found=search.trim()?plan.tests.filter(t=>ids.has(t.id)&&(t.system+' '+t.screen+' '+t.scenario+' '+t.id).toLowerCase().includes(search.trim().toLowerCase())):[];const screen=screens.find(s=>s.testIds.includes(test.id))!;return <div className="test-picker"><Input aria-label="البحث عن اختبار في جميع الأنظمة المصرح بها" placeholder="ابحث بالنظام أو الشاشة أو اسم الاختبار أو معرّفه…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="picker-search-results"><p>{found.length} نتيجة</p>{found.map(t=><Button variant="outline" key={t.id} onClick={()=>{onSelect(t.id);setSearch('');}}>{t.system} · {t.screen} · {t.scenario} · {t.id}</Button>)}</div>}<div className="selector-row"><label>النظام<Choice value={test.system} label={'نظام '+prefix} onChange={s=>onSelect(screens.find(x=>x.system===s)!.testIds[0])} options={plan.systems.filter(s=>screens.some(x=>x.system===s)).map(s=>[s,s])}/></label><label>الشاشة<Choice value={screen.id} label={'شاشة '+prefix} onChange={s=>onSelect(screens.find(x=>x.id===s)!.testIds[0])} options={screens.filter(s=>s.system===test.system).map(s=>[s.id,s.name])}/></label></div><label className="test-selector">{prefix==='المحرر'?'الاختبار المراد تحريره':'الاختبار المراد تهيئته'}<Choice value={test.id} label={'اختبار '+prefix} onChange={onSelect} options={screen.testIds.map(id=>{const t=plan.tests.find(t=>t.id===id)!;return [id,t.scenario+' — '+id];})}/></label></div>;}
export function Preparation({screens,test,initial,form,onSelect,onSave,onDirty,onExecute,onEdit,readOnly}:{screens:Screen[];test:TestCase;initial?:TestData;form:TestForm;onSelect:(id:string)=>void;onSave:(v:TestData)=>Promise<TestData>;onDirty:(v:boolean)=>void;onExecute:()=>void;onEdit?:()=>void;readOnly:boolean}){
 const issue=preparationIssue(initial,form);const inherited=!!initial&&JSON.stringify(hydrateData(test.id,form,initial))!==JSON.stringify(initial);
 const [value,setValue]=useState(hydrateData(test.id,form,initial)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[modified,setModified]=useState(false);
 const [prevSync,setPrevSync]=useState({initial,form});if(initial!==prevSync.initial||form!==prevSync.form){setPrevSync({initial,form});setValue(hydrateData(test.id,form,initial));setModified(false);setError('');}useEffect(()=>{onDirty(false);},[initial,form,onDirty]);
 function update(f:FormField,v:FieldValue){setValue(p=>f.kind==='custom'?{...p,customValues:{...p.customValues,[f.id]:v}}:{...p,[f.key!]:v});setModified(true);onDirty(true);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await onSave(validateConfiguredData(value,form));setValue(d);setModified(false);onDirty(false);toast.success('حُفظت بيانات تهيئة الاختبار');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="plan-surface admin-surface"><div className="section-heading"><div><h2><Database size={22}/>تهيئة البيانات الأساسية</h2><p>بيانات مستقلة لكل اختبار، تظهر للمنفذ داخل نموذج التنفيذ.</p></div><div className="action-cluster">{onEdit&&<Button variant="outline" onClick={onEdit}><SlidersHorizontal size={16}/>تحرير نموذج هذا الاختبار</Button>}<Button variant="outline" onClick={onExecute}><Play size={16}/>فتح نموذج التنفيذ</Button></div></div>
 <TestPicker screens={screens} test={test} onSelect={onSelect} prefix="التهيئة"/>
 <div className="context-banner"><div><b>{test.screen}</b><p>{test.scenario} <code>{test.id}</code></p></div><span className={'data-status '+(initial?.ready&&!issue?'ready':'')}>{issue?'تحتاج مراجعة التهيئة':initial?.ready?<><CheckCheck size={16}/>البيانات جاهزة</>:initial?'مسودة بيانات':'لم تُجهّز البيانات'}</span></div>
 <div className="definition-actions no-print"><Button variant="outline" onClick={()=>downloadForm(form,'preparation',dataValues(value),'docx')}>تصدير DOCX</Button><Button variant="outline" onClick={()=>downloadForm(form,'preparation',dataValues(value),'xlsx')}>تصدير XLSX</Button></div><FormVersion form={form}/>{issue&&<p role="status" className="access-note">تغيّر نموذج الاختبار وتحتاج التهيئة إلى استكمال: {issue}</p>}<div className="prep-workspace"><form onSubmit={save} className="prep-form">{inherited&&<p className="access-note">أُكملت الحقول الفارغة بقيم النموذج الجديد. احفظ بيانات التهيئة لتظهر هذه المدخلات في التنفيذ.</p>}{!readOnly&&<ApplyFormDefaults form={form} group="preparation" values={dataValues(value)} disabled={busy} onApply={changes=>{setValue(p=>applyDefaultChanges(p,changes));setModified(true);onDirty(true);setError('');}}/>}<fieldset disabled={readOnly||busy} className="settings-fields"><h3>بيانات التنفيذ المحددة</h3><ConfiguredFields form={form} group="preparation" values={dataValues(value)} onChange={update} required={value.ready} disabled={readOnly||busy}/></fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<div className="save-row">{!readOnly&&<Button type="submit" disabled={busy}><Save size={17}/>{busy?'جارٍ الحفظ…':'حفظ بيانات التهيئة'}</Button>}<span>{readOnly?'عرض فقط':modified?'تعديلات لم تُحفظ':value.updatedAt?'آخر حفظ: '+new Date(value.updatedAt).toLocaleString('ar-YE',{timeZone:'Asia/Aden'}):'لم تُحفظ بيانات بعد'}</span></div></form>
 <aside className="prep-reference"><h3>تعليمات الاختبار</h3><ConfiguredFields form={form} group="instructions" values={{}} onChange={()=>{}}/></aside></div></section>;
}
export function PreparedSummary({data,form,onOpen}:{data?:TestData;form:TestForm;onOpen:()=>void}){const issue=preparationIssue(data,form);const values=data?dataValues(data):{};const fields=form.fields.filter(f=>f.active&&f.group==='preparation'&&f.key!=='ready'&&!['heading','note'].includes(f.type));return <section className="prepared-summary"><div className="prepared-heading"><h4><Database size={17}/>بيانات الاختبار المحددة</h4><Button type="button" size="sm" variant="outline" onClick={onOpen}>{data?'عرض أو تعديل التهيئة':'تهيئة هذا الاختبار'}</Button></div>{data?<><span className={'data-status '+(data.ready&&!issue?'ready':'')}>{issue?'تحتاج مراجعة التهيئة':data.ready?'جاهزة للتنفيذ':'مسودة — لم تُعلن الجاهزية'}</span>{issue&&<p className="prep-summary-notes">{issue}</p>}<dl>{fields.map(f=>{const v=values[f.id];return v===undefined||v===''?null:<div key={f.id} className={f.wide?'wide':''}><dt>{f.label}</dt><dd>{typeof v==='boolean'?v?'نعم':'لا':v}</dd></div>;})}</dl></>:<p>لم تُجهّز بيانات هذا الاختبار بعد.</p>}</section>;}
