"use client";
import {useCallback,useEffect,useState} from 'react';
import {Users,UserPlus,Save,ShieldCheck,RefreshCw,Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {plan} from '../lib/domain/model';
import {roleLabels,rolePermissions,permissionLabels,type AppUser,type Role,type Permission} from '../lib/domain/admin-model';
import {Choice,Tick,readResponse,put} from './form-fields';
export function UserManager({onDirty,navigate}:{onDirty:(v:boolean)=>void;navigate:(action:()=>void)=>void}){
 const [users,setUsers]=useState<AppUser[]>([]),[value,setValue]=useState<AppUser|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await readResponse<{users:AppUser[]}>(await fetch('/api/users',{cache:'no-store'}));setUsers(d.users);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{let cancelled=false;void(async()=>{try{const d=await readResponse<{users:AppUser[]}>(await fetch('/api/users',{cache:'no-store'}));if(!cancelled){setUsers(d.users);setError('');}}catch(e){if(!cancelled)setError((e as Error).message);}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
 function select(user:AppUser|null){navigate(()=>{setValue(user);setError('');onDirty(false);});}
 function add(){select({id:'',name:'',email:'',role:'tester',permissions:rolePermissions('tester'),systems:[...plan.systems],active:true,version:0,updatedAt:''});}
 function update(p:Partial<AppUser>){setValue(v=>v?{...v,...p}:null);onDirty(true);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await put<{user:AppUser}>('/api/users',value);setUsers(p=>[...p.filter(x=>x.id!==d.user.id),d.user]);setValue(d.user);onDirty(false);toast.success('حُفظ المستخدم وصلاحياته');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=users.filter(u=>(u.name+' '+u.email).toLowerCase().includes(query.trim().toLowerCase()));
 return <section className="plan-surface admin-surface"><div className="section-heading"><div><h2><Users size={22}/>إدارة المستخدمين والصلاحيات</h2><p>حدد الإجراءات والأنظمة المتاحة لكل حساب، وأوقف صلاحياته عند الحاجة.</p></div><Button onClick={add} disabled={loading||busy}><UserPlus size={17}/>إضافة مستخدم</Button></div>
 <div className="access-note"><ShieldCheck size={20}/><p>هذه الشاشة تضبط صلاحيات الأداة فقط. حفظ مستخدم لا يمنحه وصولاً إلى رابط الموقع ولا يرسل دعوة. يظل الوصول خاضعاً لمشاركة الموقع الخاص، وتُطبّق الصلاحيات بعد دخوله بحسابه المحدد.</p></div>
 <div className="user-workspace"><div className="user-list"><div className="filters"><div className="search-wrap"><Search size={18}/><Input aria-label="البحث عن مستخدم" placeholder="الاسم أو البريد الإلكتروني" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button variant="outline" aria-label="تحديث المستخدمين" onClick={()=>navigate(()=>{setValue(null);onDirty(false);void load();})} disabled={loading||busy}><RefreshCw size={16}/></Button></div>{loading?<p role="status" className="mini-empty">جارٍ تحميل المستخدمين…</p>:<Table className="users-table"><TableHeader><TableRow><TableHead>المستخدم</TableHead><TableHead>الدور والحالة</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{filtered.map(u=><TableRow key={u.id}><TableCell><b>{u.name}</b><small dir="ltr">{u.email}</small><small>{u.owner?'مالك الموقع':u.bound?'مرتبط بحساب دخل إلى الأداة':'بانتظار أول دخول'}</small></TableCell><TableCell>{roleLabels[u.role]}<small className={u.active?'text-success':'text-danger'}>{u.active?'فعال':'موقوف'}</small></TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>select(u)} disabled={busy}>{u.owner?'عرض':'تعديل'}</Button></TableCell></TableRow>)}</TableBody></Table>}{!loading&&!filtered.length&&<p className="mini-empty">لا يوجد مستخدم يطابق البحث.</p>}</div>
 <div className="user-detail">{value?<form onSubmit={save}><h3>{value.owner?'صلاحيات مالك الموقع':value.id?'تعديل المستخدم':'مستخدم جديد'}</h3>{value.owner&&<p className="muted compact">يحتفظ مالك الموقع بجميع الصلاحيات لضمان إمكانية إدارة الأداة.</p>}<fieldset disabled={busy||value.owner} className="settings-fields"><label htmlFor="user-name">اسم المستخدم<Input id="user-name" value={value.name} onChange={e=>update({name:e.target.value})} required maxLength={200}/></label><label htmlFor="user-email">البريد الإلكتروني للحساب<Input id="user-email" dir="ltr" type="email" value={value.email} onChange={e=>update({email:e.target.value})} disabled={!!value.id} required maxLength={254}/></label><label>الدور<Choice value={value.role} label="دور المستخدم" disabled={busy||value.owner} onChange={v=>update({role:v as Role,permissions:rolePermissions(v as Role),...(v==='admin'?{systems:[...plan.systems]}:{})})} options={Object.entries(roleLabels)}/></label><Tick checked={value.active} onChange={v=>update({active:v})}>صلاحيات الحساب فعالة</Tick><h4>الصلاحيات</h4><p className="muted compact">الدور يملأ الصلاحيات الافتراضية؛ يمكنك تعديلها أدناه.</p>{(Object.entries(permissionLabels) as [Permission,string][]).map(([p,label])=><Tick key={p} checked={value.permissions[p]} disabled={p==='view'||value.owner||busy} onChange={v=>update({permissions:{...value.permissions,[p]:v}})}>{label}</Tick>)}<h4>الأنظمة المسموح بها</h4><Tick checked={value.systems.length===plan.systems.length} onChange={v=>update({systems:v?[...plan.systems]:[]})}>جميع الأنظمة</Tick><div className="system-checks">{plan.systems.map(s=><Tick key={s} checked={value.systems.includes(s)} onChange={v=>update({systems:v?[...value.systems,s]:value.systems.filter(x=>x!==s)})}>{s}</Tick>)}</div></fieldset>{!value.owner&&<Button disabled={busy} type="submit"><Save size={17}/>{busy?'جارٍ الحفظ…':'حفظ المستخدم والصلاحيات'}</Button>}</form>:<div className="mini-empty"><Users size={30}/><p>اختر مستخدماً لتعديل صلاحياته أو أضف حساباً جديداً.</p></div>}</div></div>{error&&<p role="alert" className="form-error">{error}</p>}
 </section>;
}
