"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Search,ShieldCheck,CheckCheck,Monitor,Layers,AlertTriangle,RefreshCw,ChevronRight,FileCheck2,Clock,Users,SlidersHorizontal,Database} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster} from '@/components/ui/sonner';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {readWorkspaceLocation,writeWorkspaceLocation} from './navigation-model';
import {FormBuilder} from './form-builder';
import {UserManager} from './user-manager';
import {Preparation} from './test-preparation';
import {can,type AppUser,type TestData} from './admin-model';
import {put} from './form-fields';
import {ResultEditor} from './result-editor';
import {resolveTestForm,editorTypes,groupLabels,type TestForm,type FormRevision} from './editor-model';
import {plan,states,priorityLabels,summarize,matches,screenStatus,testMap,type Screen,type Status,type SavedState,type Result} from './model';
const number=(n:number)=>n.toLocaleString('ar-YE');
function Choice({value,onChange,label,options,disabled=false}:{value:string;onChange:(v:string)=>void;label:string;options:[string,string][];disabled?:boolean}){
 return <Select dir="rtl" value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>;
}
function StatusBadge({status}:{status:Status}){return <span className={'status '+status}>{states[status]}</span>;}
async function readResponse<T>(response:Response):Promise<T>{const data:unknown=await response.json();if(!response.ok)throw new Error((data as {error?:string}|null)?.error??'تعذر إتمام الطلب.');return data as T;}
export default function Workspace(){
 const [saved,setSaved]=useState<SavedState>({results:{},evidence:[],forms:{},testData:{},testForms:{}});const [ready,setReady]=useState(false);const [loadError,setLoadError]=useState('');const [loading,setLoading]=useState(true);
 const [view,setView]=useState('plan');const [activeTestId,setActiveTestId]=useState('');const [routeReady,setRouteReady]=useState(false);const [formReadyKey,setFormReadyKey]=useState('');const [formLoadError,setFormLoadError]=useState('');const [refreshForm,setRefreshForm]=useState(0);
 const [system,setSystem]=useState('all');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [priority,setPriority]=useState('all');const [tab,setTab]=useState('plan');
 const [selected,setSelected]=useState<{screenId:string;testId:string}|null>(null);const [dirty,setDirty]=useState(false);const [confirm,setConfirm]=useState(false);const pending=useRef<null|(()=>void)>(null);const dirtyRef=useRef(dirty);useEffect(()=>{dirtyRef.current=dirty;},[dirty]);
 const navigate=useCallback((action:()=>void)=>{if(dirty){pending.current=action;setConfirm(true);}else action();},[dirty]);
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const data=await readResponse<SavedState>(await fetch('/api/results',{cache:'no-store'}));setSaved(data);setReady(true);setRefreshForm(n=>n+1);}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{let cancelled=false;void(async()=>{try{const data=await readResponse<SavedState>(await fetch('/api/results',{cache:'no-store'}));if(!cancelled){setSaved(data);setReady(true);setRefreshForm(n=>n+1);}}catch(e){if(!cancelled)setLoadError((e as Error).message);}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
 const user=saved.user;const allowedSystems=plan.systems.filter(s=>user?.systems.includes(s));const allowedScreens=plan.screens.filter(s=>allowedSystems.includes(s.system));const allowedTests=plan.tests.filter(t=>allowedSystems.includes(t.system));
 const activeTest=allowedTests.find(t=>t.id===activeTestId)??allowedTests[0];
 function selectTest(id:string){const t=allowedTests.find(t=>t.id===id);if(!t)return;setActiveTestId(id);setSelected({screenId:allowedScreens.find(s=>s.testIds.includes(id))!.id,testId:id});}
 useEffect(()=>{if(!ready||routeReady)return;void Promise.resolve().then(()=>{const location=readWorkspaceLocation(window.location.search,allowedTests.map(t=>t.id));if(!new URLSearchParams(window.location.search).has('test')){const recent=Object.values(saved.testForms).filter(f=>allowedTests.some(t=>t.id===f.testId)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];if(recent)location.testId=recent.testId;}setActiveTestId(location.testId);setView(location.view==='builder'&&!can(user!,'design')||location.view==='users'&&!can(user!,'manageUsers')?'plan':location.view);if(location.execute){const s=allowedScreens.find(s=>s.testIds.includes(location.testId));if(s)setSelected({screenId:s.id,testId:location.testId});}setRouteReady(true);});},[ready,routeReady,user,allowedTests,saved.testForms,allowedScreens]);
 useEffect(()=>{if(!routeReady)return;window.history.replaceState(null,'',window.location.pathname+writeWorkspaceLocation({view,testId:activeTestId,execute:!!selected}));},[routeReady,view,activeTestId,selected]);
 const formKey=routeReady&&activeTest&&(view==='builder'||view==='prepare'||view==='plan'&&selected)?view+':'+activeTest.id:'';
 useEffect(()=>{if(!formKey||!activeTest)return;const controller=new AbortController();void(async()=>{await Promise.resolve();setFormReadyKey('');setFormLoadError('');try{const d=await readResponse<{form:TestForm;revisions:FormRevision[]}>(await fetch('/api/test-forms?testId='+encodeURIComponent(activeTest.id)+(view==='builder'?'':'&mode=published'),{cache:'no-store',signal:controller.signal}));if(controller.signal.aborted)return;if(d.form.testId!==activeTest.id)throw new Error('تعذر مطابقة نموذج الاختبار.');setSaved(p=>JSON.stringify(p.testForms[d.form.testId])===JSON.stringify(d.form)?p:{...p,testForms:{...p.testForms,[d.form.testId]:d.form}});setFormReadyKey(formKey);}catch(e){if(!controller.signal.aborted)setFormLoadError((e as Error).message);}})();return()=>controller.abort();},[formKey,refreshForm,activeTest,view]);
 const permit=(p:Parameters<typeof can>[1],system?:string)=>!!user&&can(user,p,system);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const summary=summarize(allowedTests,saved.results);
 const completedScreens=allowedScreens.filter(s=>screenStatus(s.testIds.map(id=>testMap.get(id)!),saved.results)==='passed').length;
 const filtered=allowedTests.filter(t=>(system==='all'||t.system===system)&&(status==='all'||(saved.results[t.id]?.status??'planned')===status)&&(priority==='all'||t.priority===priority)&&matches(t,query,saved.results[t.id]));
 const cards=allowedScreens.filter(s=>filtered.some(t=>s.testIds.includes(t.id)));
 const stalled=filtered.filter(t=>['failed','blocked'].includes(saved.results[t.id]?.status));
 const currentScreen=selected?allowedScreens.find(s=>s.id===selected.screenId):undefined;
 const currentTest=selected?activeTest:undefined;
 function open(screen:Screen,testId?:string){navigate(()=>{setView('plan');selectTest(testId??screen.testIds.find(id=>filtered.some(t=>t.id===id))??screen.testIds[0]);window.scrollTo({top:0,behavior:'smooth'});});}
 const save=useCallback(async(input:unknown)=>{const value=input;const data=await readResponse<{result:Result}>(await fetch('/api/results',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}));setSaved(p=>({...p,results:{...p.results,[data.result.id]:data.result}}));setDirty(false);return data.result;},[]);
 const saveForm=useCallback(async(v:TestForm)=>{const d=await put<{form:TestForm;revisions:FormRevision[]}>('/api/test-forms',v);const verified=await readResponse<{form:TestForm;revisions:FormRevision[]}>(await fetch('/api/test-forms?testId='+encodeURIComponent(v.testId),{cache:'no-store'}));setSaved(p=>({...p,testForms:{...p.testForms,[verified.form.testId]:verified.form}}));if(verified.form.testId!==v.testId||verified.form.version!==d.form.version||JSON.stringify(verified.form.fields)!==JSON.stringify(d.form.fields))throw new Error('تغيّر النموذج أثناء التحقق من الحفظ؛ راجع أحدث إصدار.');setDirty(false);return verified.form;},[]);
 const saveData=useCallback(async(v:TestData)=>{const d=await put<{testData:TestData}>('/api/test-data',v);setSaved(p=>({...p,testData:{...p.testData,[d.testData.testId]:d.testData}}));setDirty(false);return d.testData;},[]);
 function openPrep(id:string){navigate(()=>{setView('prepare');selectTest(id);window.scrollTo({top:0,behavior:'smooth'});});}
 function openBuilder(id?:string){navigate(()=>{selectTest(id??activeTest?.id??'');setView('builder');window.scrollTo({top:0,behavior:'smooth'});});}
 const editTest=activeTest;const prepTest=activeTest;
 const testForms=useMemo(()=>Object.fromEntries(plan.screens.flatMap(s=>s.testIds.map(id=>[id,resolveTestForm(id,saved.forms[s.id],saved.testForms[id])]))),[saved.forms,saved.testForms]);
 const selectTestRef=useRef(selectTest);useEffect(()=>{selectTestRef.current=selectTest;});
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options?:{signal?:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();
  const add=(tool:object)=>{try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};
  add({name:'read_onyx_progress',description:'Read saved ONYX testing progress and stalled tests.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');const d=await readResponse<SavedState>(await fetch('/api/results',{cache:'no-store'}));setSaved(d);return {summary:summarize(plan.tests.filter(t=>d.user!.systems.includes(t.system)),d.results),stalled:plan.tests.filter(t=>d.user!.systems.includes(t.system)).filter(t=>['failed','blocked'].includes(d.results[t.id]?.status)).map(t=>({id:t.id,system:t.system,screen:t.screen,status:d.results[t.id].status}))};}});
  add({name:'open_onyx_screen_form',description:'Open one verified ONYX screen form. Does not save a result.',inputSchema:{type:'object',properties:{testId:{type:'string'}},required:['testId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{testId:string})=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');const s=plan.screens.find(s=>s.testIds.includes(input.testId));if(!s||!user?.systems.includes(s.system))throw new Error('الاختبار غير موجود أو غير مسموح.');setView('plan');selectTestRef.current(input.testId);return {screen:s.name,testId:input.testId};}});
  add({name:'save_onyx_test_result',description:'Save the actual result, status, notes and evidence link for one verified test. The tester is always the authenticated user. Version must match saved state.',inputSchema:{type:'object',properties:{id:{type:'string'},status:{type:'string',enum:Object.keys(states)},actual:{type:'string'},notes:{type:'string'},evidenceUrl:{type:'string'},documentNumber:{type:'string'},linkedDocumentNumber:{type:'string'},customValues:{type:'object',additionalProperties:{type:['string','boolean']}},version:{type:'integer',minimum:0}},required:['id','status','actual','notes','evidenceUrl','documentNumber','linkedDocumentNumber','customValues','version'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');const r=await save(input);return {id:r.id,status:r.status,version:r.version};}});
  add({name:'read_onyx_test_setup',description:'Read saved preparation data, custom field definitions and result for one authorized test.',inputSchema:{type:'object',properties:{testId:{type:'string'}},required:['testId'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:{testId:string})=>{const t=testMap.get(input.testId);if(!t||!user?.systems.includes(t.system))throw new Error('الاختبار غير مسموح.');const d=await readResponse<SavedState>(await fetch('/api/results',{cache:'no-store'}));const s=plan.screens.find(s=>s.testIds.includes(t.id))!;return {test:t,form:resolveTestForm(t.id,d.forms[s.id],d.testForms[t.id]),preparation:d.testData[t.id]??null,result:d.results[t.id]??null};}});
  add({name:'save_onyx_test_data',description:'Save preparation data for one verified test. Setting ready requires visible required fields in the configured test form. Does not create ONYX documents.',inputSchema:{type:'object',properties:{testId:{type:'string'},party:{type:'string'},amount:{type:'string'},currency:{type:'string'},documentNumber:{type:'string'},date:{type:'string'},branch:{type:'string'},notes:{type:'string'},customValues:{type:'object',additionalProperties:{type:['string','boolean']}},ready:{type:'boolean'},version:{type:'integer',minimum:0}},required:['testId','party','amount','currency','documentNumber','date','branch','notes','customValues','ready','version'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:TestData)=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');const r=await saveData(input);return {testId:r.testId,ready:r.ready,version:r.version};}});
  const customFieldSchema={type:'object',properties:{id:{type:'string'},label:{type:'string'},kind:{type:'string',enum:['builtin','custom']},key:{type:'string'},type:{type:'string',enum:Object.keys(editorTypes)},group:{type:'string',enum:Object.keys(groupLabels)},help:{type:'string'},placeholder:{type:'string'},required:{type:'boolean'},wide:{type:'boolean'},active:{type:'boolean'},options:{type:'array',items:{type:'string'}},defaultValue:{type:['string','boolean']},min:{type:'string'},max:{type:'string'}},required:['id','kind','label','type','group','help','placeholder','required','wide','active','options','defaultValue','min','max'],additionalProperties:false};
  add({name:'save_onyx_test_form',description:'Save the full form for one verified test, including builtin fields and instructions. Read setup first and retain field identities. Hide saved fields instead of deleting them. Requires design permission.',inputSchema:{type:'object',properties:{testId:{type:'string'},screenId:{type:'string'},fields:{type:'array',maxItems:140,items:customFieldSchema},version:{type:'integer',minimum:0},baseVersion:{type:'integer',minimum:0}},required:['testId','screenId','fields','version','baseVersion'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:TestForm)=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');const r=await saveForm(input);return {testId:r.testId,version:r.version};}});
  add({name:'read_onyx_users',description:'Read configured users and permissions. Requires user management permission.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>readResponse<{users:AppUser[]}>(await fetch('/api/users',{cache:'no-store'}))});
  add({name:'save_onyx_user_permissions',description:'Create or update application permissions for a user. Does not share the Site, send an invitation or grant hosting access. Owner permissions are immutable. Requires user management permission.',inputSchema:{type:'object',properties:{id:{type:'string'},email:{type:'string'},name:{type:'string'},role:{type:'string',enum:['admin','designer','preparer','tester','viewer']},permissions:{type:'object',properties:{view:{type:'boolean'},execute:{type:'boolean'},design:{type:'boolean'},prepare:{type:'boolean'},manageUsers:{type:'boolean'}},required:['view','execute','design','prepare','manageUsers'],additionalProperties:false},systems:{type:'array',items:{type:'string',enum:plan.systems}},active:{type:'boolean'},version:{type:'integer',minimum:0}},required:['id','email','name','role','permissions','systems','active','version'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(dirtyRef.current)throw new Error('احفظ التعديلات الحالية أولاً.');return put<{user:AppUser}>('/api/users',input);}});
  return ()=>controller.abort();
 },[save,saveData,saveForm,user]);
 return <SidebarProvider className="shell">
 <Sidebar side="right" collapsible="none" className="systems-sidebar">
  <SidebarHeader><div className="brand"><div className="brand-symbol"><CheckCheck size={26}/></div><div><b dir="ltr">ONYX</b><span>اختبارات الترقية</span></div></div></SidebarHeader>
  <SidebarContent><SidebarMenu className="workspace-nav"><SidebarMenuItem><SidebarMenuButton isActive={view==='plan'} onClick={()=>navigate(()=>{setView('plan');if(activeTest)selectTest(activeTest.id);})}><FileCheck2 size={18}/><span>تنفيذ الاختبارات</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={view==='prepare'} onClick={()=>openPrep(activeTest?.id??'')}><Database size={18}/><span>تهيئة البيانات الأساسية</span></SidebarMenuButton></SidebarMenuItem>{permit('design')&&<SidebarMenuItem><SidebarMenuButton isActive={view==='builder'} onClick={()=>openBuilder()}><SlidersHorizontal size={18}/><span>محرر النماذج</span></SidebarMenuButton></SidebarMenuItem>}{permit('manageUsers')&&<SidebarMenuItem><SidebarMenuButton isActive={view==='users'} onClick={()=>navigate(()=>setView('users'))}><Users size={18}/><span>المستخدمون والصلاحيات</span></SidebarMenuButton></SidebarMenuItem>}</SidebarMenu><p className="nav-caption">أنظمة خطة الاختبار</p><SidebarMenu>
   <SidebarMenuItem><SidebarMenuButton isActive={system==='all'&&view==='plan'} onClick={()=>navigate(()=>{setView('plan');setSystem('all');setSelected(null);})}><Layers size={18}/><span>جميع الأنظمة</span><small>{number(allowedScreens.length)}</small></SidebarMenuButton></SidebarMenuItem>
   {allowedSystems.map(name=><SidebarMenuItem key={name}><SidebarMenuButton isActive={system===name&&view==='plan'} onClick={()=>navigate(()=>{setView('plan');setSystem(name);setSelected(null);})}><span>{name}</span><small>{number(allowedScreens.filter(s=>s.system===name).length)}</small></SidebarMenuButton></SidebarMenuItem>)}
  </SidebarMenu></SidebarContent>
  <SidebarFooter><div className="private-note"><ShieldCheck size={18}/><span>موقع خاص · صلاحيات محددة</span></div><p className="sidebar-source">خطة العمليات الأساسية<br/>الإصدار 2.1</p></SidebarFooter>
 </Sidebar>
 <main className="main">
  <header className="topbar"><div><span className="eyebrow">الإدارة العامة للشؤون المالية{user?' · '+user.name:''}</span><h1>اختبارات ترقية <span dir="ltr">ONYX</span></h1></div><Button variant="outline" onClick={()=>navigate(()=>void load())} disabled={loading} className="refresh"><RefreshCw size={16} className={loading?'spinning':''}/>{loading?'جارٍ التحديث':'تحديث النتائج'}</Button></header>
  <div className="mobile-workspace-nav"><Tabs dir="rtl" value={view} onValueChange={v=>v==='builder'?openBuilder():navigate(()=>{setView(v);if(v==='plan'&&activeTest)selectTest(activeTest.id);})}><TabsList><TabsTrigger value="plan">الاختبارات</TabsTrigger><TabsTrigger value="prepare">التهيئة</TabsTrigger>{permit('design')&&<TabsTrigger value="builder">المحرر</TabsTrigger>}{permit('manageUsers')&&<TabsTrigger value="users">المستخدمون</TabsTrigger>}</TabsList></Tabs></div>
  <section className={'overview '+(view!=='plan'?'compact-overview':'')} aria-label="ملخص التقدم">
   <div className="progress-card"><div className="progress-heading"><span><Activity size={19}/>التقدم العام</span><strong>{ready?number(summary.percent)+'٪':'—'}</strong></div><Progress value={ready?summary.percent:0} aria-label="نسبة الاختبارات المحسومة"/><p>{ready?number(summary.completed):'—'} من {number(summary.total)} اختباراً حُسمت نتيجتها <span>ناجح أو فاشل</span></p><div className="screen-progress"><Monitor size={16}/>{ready?number(completedScreens):'—'} من {number(allowedScreens.length)} شاشة اجتازت جميع اختباراتها</div></div>
   <div className="metric"><span className="metric-icon success"><CheckCheck size={22}/></span><span>اختبارات ناجحة</span><strong>{ready?number(summary.passed):'—'}</strong></div>
   <button className="metric metric-button" onClick={()=>navigate(()=>{setView('plan');setSelected(null);setSystem('all');setQuery('');setStatus('all');setPriority('all');setTab('stalled');})}><span className="metric-icon trouble"><AlertTriangle size={22}/></span><span>اختبارات متعثرة</span><strong>{ready?number(summary.stalled):'—'}</strong><small>فاشلة أو متعذرة</small></button>
   <div className="metric"><span className="metric-icon neutral"><Clock size={22}/></span><span>بانتظار التنفيذ</span><strong>{ready?number(summary.planned):'—'}</strong><small>قيد التنفيذ: {ready?number(summary.in_progress):'—'}</small></div>
  </section>
  {loadError&&<div role="alert" className="error-panel"><AlertTriangle size={18}/><span>{loadError}</span><Button variant="outline" onClick={()=>void load()}>إعادة المحاولة</Button></div>}
  {view==='plan'&&<div className="mobile-system"><Choice value={system} onChange={v=>navigate(()=>{setSystem(v);setSelected(null);})} label="النظام" options={[['all','جميع الأنظمة'],...allowedSystems.map(s=>[s,s] as [string,string])]}/></div>}
  {view==='plan'&&(!selected?<section className="plan-surface">
   <div className="section-heading"><div><h2>{system==='all'?'خطة الاختبار':system}</h2><p>{system==='all'?number(allowedSystems.length)+' نظاماً · '+number(allowedScreens.length)+' نموذج شاشة مستقل':number(allowedScreens.filter(s=>s.system===system).length)+' نموذج شاشة مستقل · '+number(allowedTests.filter(t=>t.system===system).length)+' اختباراً تنفيذياً'}</p></div><Tabs dir="rtl" value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="plan">الشاشات</TabsTrigger><TabsTrigger value="stalled">المتعثرة</TabsTrigger></TabsList></Tabs></div>
   <div className="filters"><div className="search-wrap"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label="البحث" placeholder="ابحث عن شاشة أو عملية أو رقم اختبار أو وثيقة…"/></div><Choice value={status} onChange={setStatus} label="تصفية حسب الحالة" options={[['all','جميع الحالات'],...Object.entries(states)] as [string,string][]}/><Choice value={priority} onChange={setPriority} label="تصفية حسب الأولوية" options={[['all','جميع الأولويات'],...Object.entries(priorityLabels)]}/>{(query||status!=='all'||priority!=='all')&&<Button variant="ghost" onClick={()=>{setQuery('');setStatus('all');setPriority('all');}}>مسح التصفية</Button>}</div>
   {plan.pending.some(t=>allowedSystems.includes(t.system)&&(system==='all'||t.system===system))&&<div className="pending-notice"><AlertTriangle size={18}/><span>٣ حالات في إدارة المعلومات تنتظر توثيق اسم الشاشة الفعلي؛ لم تُدرج في نماذج التنفيذ أو نسبة الإنجاز.</span><details><summary>عرض الحالات</summary>{plan.pending.filter(t=>allowedSystems.includes(t.system)).map(t=><p key={t.id}><b>{t.scenario}</b> <code>{t.id}</code></p>)}</details></div>}
   {!ready&&!loadError&&<div className="empty-state">جارٍ تحميل النتائج المحفوظة…</div>}
   {ready&&tab==='plan'&&<><div className="list-caption"><span>{number(cards.length)} شاشة تطابق البحث والتصفية</span><span>افتح الشاشة لتنفيذ عملياتها</span></div><div className="screen-grid">{cards.map(s=>{const tests=s.testIds.map(id=>testMap.get(id)!);const n=summarize(tests,saved.results);return <button key={s.id} className="screen-card" onClick={()=>open(s)}><div className="card-top"><Monitor size={20}/><StatusBadge status={screenStatus(tests,saved.results)}/></div><small>{s.system}</small><h3>{s.name}</h3><p>{number(tests.length)} {tests.length===1?'اختبار تنفيذي':'اختبارات تنفيذية'}</p><div className="card-bottom"><span>{number(n.completed)} / {number(n.total)} حُسمت</span><span>فتح النموذج <ChevronRight size={16}/></span></div><Progress value={n.percent} aria-label={'تقدم '+s.name}/></button>;})}</div>{!cards.length&&<div className="empty-state"><Monitor size={30}/><h3>لا توجد شاشات مطابقة</h3><p>غيّر كلمات البحث أو خيارات التصفية.</p></div>}</>}
   {ready&&tab==='stalled'&&<>{stalled.length?<Table className="stalled-table"><TableHeader><TableRow><TableHead>الشاشة والنظام</TableHead><TableHead>العملية</TableHead><TableHead>الحالة</TableHead><TableHead>النتيجة الفعلية</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{stalled.map(t=><TableRow key={t.id}><TableCell><b>{t.screen}</b><small>{t.system}</small></TableCell><TableCell>{t.scenario}<code>{t.id}</code></TableCell><TableCell><StatusBadge status={saved.results[t.id].status}/></TableCell><TableCell className="actual-cell">{saved.results[t.id].actual}</TableCell><TableCell><Button variant="outline" onClick={()=>open(plan.screens.find(s=>s.testIds.includes(t.id))!,t.id)}>فتح الاختبار</Button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><FileCheck2 size={32}/><h3>لا توجد اختبارات متعثرة ضمن التصفية</h3><p>تظهر هنا الحالات الفاشلة والمتعذرة بعد حفظ نتائجها.</p></div>}</>}
  </section>:currentScreen&&currentTest&&<section className="screen-form">
   <div className="form-heading"><Button variant="ghost" onClick={()=>navigate(()=>setSelected(null))}><ChevronRight size={18}/>قائمة الشاشات</Button><span>{currentScreen.system}</span></div>
   <div className="form-title"><div><span className="eyebrow">نموذج اختبار شاشة مستقل</span><h2>{currentScreen.name}</h2></div><StatusBadge status={screenStatus(currentScreen.testIds.map(id=>testMap.get(id)!),saved.results)}/></div>
   <div className="test-workspace"><div className="case-list"><h3>العمليات التنفيذية <span>{number(currentScreen.testIds.length)}</span></h3>{currentScreen.testIds.map((id,i)=>{const t=testMap.get(id)!;return <button className={id===currentTest.id?'case-choice active':'case-choice'} key={id} onClick={()=>navigate(()=>selectTest(id))}><span className="case-number">{number(i+1)}</span><div><b>{t.scenario}</b><small>{t.operation}</small><StatusBadge status={saved.results[id]?.status??'planned'}/></div></button>;})}</div>
   {formReadyKey!==formKey?<div className="editor empty-state" role="status">{formLoadError?<><p role="alert">{formLoadError}</p><Button variant="outline" onClick={()=>setRefreshForm(n=>n+1)}>إعادة تحميل النموذج</Button></>:'جارٍ تحميل أحدث نموذج لهذا الاختبار…'}</div>:<ResultEditor user={user!} form={saved.results[currentTest.id]?.formSnapshot??testForms[currentTest.id]} onEdit={permit('design',currentTest.system)?()=>openBuilder(currentTest.id):undefined} data={saved.testData[currentTest.id]} onPrep={()=>openPrep(currentTest.id)} readOnly={!permit('execute',currentTest.system)} key={currentTest.id} test={currentTest} initial={saved.results[currentTest.id]} evidence={saved.evidence.filter(e=>e.testId===currentTest.id&&(e.runId??'')===(saved.results[currentTest.id]?.runId??''))} onDirty={setDirty} onSave={save} onLifecycle={r=>{setSaved(p=>({...p,results:{...p.results,[r.id]:r}}));setDirty(false);}} onEvidence={e=>setSaved(p=>({...p,evidence:[...p.evidence,e]}))}/>}
   </div>
  </section>)}
  {ready&&routeReady&&view==='builder'&&permit('design')&&editTest&&formReadyKey===formKey&&<FormBuilder key={editTest.id} screens={allowedScreens.filter(s=>permit('design',s.system))} test={editTest} user={user!} initial={testForms[editTest.id]} onSelect={id=>navigate(()=>selectTest(id))} onSave={saveForm} onDirty={setDirty} onExecute={()=>open(allowedScreens.find(s=>s.testIds.includes(editTest.id))!,editTest.id)} onPrepare={()=>openPrep(editTest.id)}/>}
  {ready&&view==='users'&&permit('manageUsers')&&<UserManager onDirty={setDirty} navigate={navigate}/>}
  {ready&&routeReady&&view==='prepare'&&prepTest&&formReadyKey===formKey&&<Preparation key={prepTest.id} screens={allowedScreens} test={prepTest} initial={saved.testData[prepTest.id]} form={testForms[prepTest.id]} onEdit={permit('design',prepTest.system)?()=>openBuilder(prepTest.id):undefined} onSelect={id=>navigate(()=>selectTest(id))} onSave={saveData} onDirty={setDirty} readOnly={!permit('prepare',prepTest.system)} onExecute={()=>open(allowedScreens.find(s=>s.testIds.includes(prepTest.id))!,prepTest.id)}/>}
  {ready&&['builder','prepare'].includes(view)&&formReadyKey!==formKey&&<section className="plan-surface empty-state" role="status">{formLoadError?<><p role="alert">{formLoadError}</p><Button variant="outline" onClick={()=>setRefreshForm(n=>n+1)}>إعادة تحميل النموذج</Button></>:'جارٍ تحميل أحدث نموذج لهذا الاختبار…'}</section>}
  <footer className="page-footer"><span>المصدر: خطة اختبار العمليات الأساسية بحسب الشاشات V2.1</span><span>الأسماء كما وردت في المصدر</span></footer>
 </main>
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>لديك تعديلات لم تُحفظ</AlertDialogTitle><AlertDialogDescription>يمكنك البقاء لحفظ البيانات، أو الانتقال والتخلي عن هذه التعديلات.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>البقاء في النموذج</AlertDialogCancel><AlertDialogAction onClick={()=>{setDirty(false);pending.current?.();pending.current=null;}}>التخلي والانتقال</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Toaster dir="rtl" position="bottom-left" richColors/>
 </SidebarProvider>;
}