import type {FormField,TestForm} from './editor-model';
import type {Values,FieldValue} from './admin-model';
export const advancedTypes={email:'بريد إلكتروني',phone:'هاتف',integer:'عدد صحيح',percent:'نسبة مئوية',code:'رمز أو رقم مستند',time:'وقت',datetime:'تاريخ ووقت',duration:'مدة',multiselect:'اختيار متعدد',radio:'اختيار مفرد',searchselect:'قائمة قابلة للبحث',json:'مدخل JSON',table:'جدول قابل للتحرير',calculated:'قيمة محسوبة',rating:'تقييم',range:'شريط نطاق',consent:'إقرار بالموافقة',separator:'فاصل',space:'مساحة',alert:'تنبيه',section:'قسم قابل للطي'} as const;
export const nonInputs=['content','heading','note','separator','space','alert','section','user','file'];
export type Condition={fieldId:string;operator:'eq'|'ne'|'gt'|'lt'|'filled';value:string;action:'show'|'require'|'disable'};
export type Column={id:string;label:string;type:'text'|'number'|'date'|'boolean';required:boolean;width:number};
export type ExtraProperties={layout?:{desktop:number;tablet:number;mobile:number;rows:number;height:number;gap:number};appearance?:{color:string;background:string;fontSize:number;radius:number};readOnly?:boolean;disabled?:boolean;printVisible?:boolean;section?:string;preparationSource?:string;condition?:Condition;formula?:string;precision?:number;columns?:Column[];optionItems?:{value:string;label:string;disabled:boolean}[]};
export function validateExtras(f:FormField,ids:Set<string>):ExtraProperties{
 const out:ExtraProperties={};
 if(f.layout){const v=f.layout;for(const k of ['desktop','tablet','mobile'] as const)if(!Number.isInteger(v[k])||v[k]<1||v[k]>12)throw new Error('عرض الحقل يجب أن يكون من ١ إلى ١٢ عموداً.');if(!Number.isInteger(v.rows)||v.rows<1||v.rows>30||!Number.isFinite(v.height)||v.height<0||v.height>1000||!Number.isFinite(v.gap)||v.gap<0||v.gap>80)throw new Error('راجع ارتفاع الحقل والمسافات.');out.layout={...v};}
 if(f.appearance){const v=f.appearance;if(!/^#[a-f0-9]{6}$/i.test(v.color)||!/^#[a-f0-9]{6}$/i.test(v.background)||!Number.isFinite(v.fontSize)||v.fontSize<14||v.fontSize>36||!Number.isFinite(v.radius)||v.radius<0||v.radius>40)throw new Error('خصائص المظهر غير صحيحة.');out.appearance={...v};}
 for(const k of ['readOnly','disabled','printVisible'] as const)if(f[k]!==undefined){if(typeof f[k]!=='boolean')throw new Error('خاصية الحقل غير صحيحة.');out[k]=f[k];}
 if(f.section!==undefined){if(typeof f.section!=='string'||f.section.length>120)throw new Error('اسم المجموعة طويل.');out.section=f.section;}
 if(f.preparationSource){if(f.group!=='execution'||!ids.has(f.preparationSource))throw new Error('مرجع التهيئة غير صحيح.');out.preparationSource=f.preparationSource;}
 if(f.condition){const c=f.condition;if(!ids.has(c.fieldId)||c.fieldId===f.id||!['eq','ne','gt','lt','filled'].includes(c.operator)||!['show','require','disable'].includes(c.action)||typeof c.value!=='string'||c.value.length>300)throw new Error('راجع شرط الحقل «'+f.label+'».');out.condition={...c};}
 if(f.formula!==undefined){if(typeof f.formula!=='string'||f.formula.length>1000)throw new Error('المعادلة طويلة.');for(const id of references(f.formula))if(!ids.has(id)||id===f.id)throw new Error('المعادلة تشير إلى حقل غير موجود أو إلى نفسها.');calculate(f.formula,{},true);out.formula=f.formula;}
 if(f.precision!==undefined){if(!Number.isInteger(f.precision)||f.precision<0||f.precision>8)throw new Error('الدقة من صفر إلى ٨ منازل.');out.precision=f.precision;}
 if(f.columns){if(!Array.isArray(f.columns)||f.columns.length>30||new Set(f.columns.map(c=>c.id)).size!==f.columns.length)throw new Error('أعمدة الجدول غير صحيحة.');out.columns=f.columns.map(c=>{if(!/^[a-z0-9_-]{1,80}$/i.test(c.id)||typeof c.label!=='string'||!c.label.trim()||c.label.length>120||!['text','number','date','boolean'].includes(c.type)||typeof c.required!=='boolean'||!Number.isFinite(c.width)||c.width<60||c.width>600)throw new Error('راجع تعريف أعمدة الجدول.');return {...c};});}
 if(f.optionItems){if(!Array.isArray(f.optionItems)||f.optionItems.length>100||new Set(f.optionItems.map(o=>o.value)).size!==f.optionItems.length)throw new Error('قيم الخيارات مكررة.');out.optionItems=f.optionItems.map(o=>{if(typeof o.value!=='string'||!o.value||o.value.length>150||typeof o.label!=='string'||!o.label.trim()||o.label.length>150||typeof o.disabled!=='boolean')throw new Error('راجع الخيارات.');return {...o};});}
 return out;
}
export function references(expression:string){return [...expression.matchAll(/\[([^\]]+)\]/g)].map(m=>m[1]);}
// Small arithmetic grammar; no eval, Function, JS execution or arbitrary functions.
export function calculate(expression:string,values:Values,checking=false):string{
 if(!expression.trim())return '';
 const tokens=expression.match(/\[[^\]]+\]|\d+(?:\.\d+)?|[()+\-*/]/g)??[];if(tokens.join('')!==expression.replace(/\s/g,''))throw new Error('استخدم أرقاماً ومعرّفات حقول بين [ ] والعمليات + - * / والأقواس.');let i=0,missing=false;
 function atom():number{const t=tokens[i++];if(t==='+'||t==='-')return (t==='-'?-1:1)*atom();if(t==='('){const n=sum();if(tokens[i++]!==')')throw new Error('أقواس المعادلة غير متوازنة.');return n;}if(t?.startsWith('[')){const v=values[t.slice(1,-1)];if(v===undefined||v===''){missing=true;return 0;}if(typeof v==='boolean'||!Number.isFinite(Number(v)))throw new Error('مدخل المعادلة ليس رقماً.');return Number(v);}if(t===undefined||!/^[0-9]/.test(t))throw new Error('المعادلة غير مكتملة.');return Number(t);}
 function product(){let n=atom();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],b=atom();if(op==='/'&&b===0&&!checking)throw new Error('لا يمكن القسمة على صفر.');n=op==='*'?n*b:b===0?0:n/b;}return n;}
 function sum(){let n=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++],b=product();n=op==='+'?n+b:n-b;}return n;}
 const n=sum();if(i!==tokens.length||!Number.isFinite(n))throw new Error('المعادلة غير صحيحة أو تجاوزت الحدود.');return missing?'':String(n);
}
export function conditionMatches(c:Condition,values:Values){const v=values[c.fieldId];if(c.operator==='filled')return v!==undefined&&v!=='';if(c.operator==='eq')return String(v??'')===c.value;if(c.operator==='ne')return String(v??'')!==c.value;if(v===undefined||v==='')return false;return c.operator==='gt'?Number(v)>Number(c.value):Number(v)<Number(c.value);}
export function effectiveField(f:FormField,values:Values):FormField{const match=f.condition&&conditionMatches(f.condition,values);return {...f,active:f.active&&(!f.condition||f.condition.action!=='show'||!!match),required:f.required||!!(match&&f.condition?.action==='require'),disabled:f.disabled||!!(match&&f.condition?.action==='disable')};}
export function assertDependencies(form:TestForm){const graph=new Map(form.fields.map(f=>[f.id,[...(f.condition?[f.condition.fieldId]:[]),...references(f.formula??'')]]));const visited=new Set<string>(),stack=new Set<string>();function visit(id:string){if(stack.has(id))throw new Error('توجد علاقة دائرية في شروط أو معادلات النموذج.');if(visited.has(id))return;stack.add(id);for(const dep of graph.get(id)??[])visit(dep);stack.delete(id);visited.add(id);}for(const id of graph.keys())visit(id);}
export function computedValues(form:TestForm,input:Values){const values={...input},errors:Record<string,string>={},done=new Set<string>();function run(f:FormField){if(done.has(f.id))return;done.add(f.id);for(const id of references(f.formula??'')){const dep=form.fields.find(x=>x.id===id);if(dep?.type==='calculated')run(dep);}if(f.type==='calculated')try{const n=calculate(f.formula??'',values);values[f.id]=n===''?'':Number(n).toFixed(f.precision??2);}catch(e){errors[f.id]=(e as Error).message;}}form.fields.forEach(run);return {values,errors};}
export type AdvancedField={type:string;label:string;required:boolean;min:string;max:string;options:string[];columns?:Column[]};
export function validateAdvancedValue(f:AdvancedField,value:FieldValue,required:boolean){
 if(nonInputs.includes(f.type))return;
 if(required&&f.required&&value==='')throw new Error('الحقل «'+f.label+'» مطلوب.');if(value==='')return;
 const s=String(value);if(f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))throw new Error('البريد في «'+f.label+'» غير صحيح.');
 if(f.type==='integer'&&!/^-?\d+$/.test(s))throw new Error('أدخل عدداً صحيحاً في «'+f.label+'».');
 if(['integer','percent','rating','range','duration','calculated'].includes(f.type)&&(!Number.isFinite(Number(s))||f.min!==''&&Number(s)<Number(f.min)||f.max!==''&&Number(s)>Number(f.max)))throw new Error('راجع العدد في «'+f.label+'».');
 if(f.type==='json')try{JSON.parse(s);}catch{throw new Error('JSON في «'+f.label+'» غير صالح.');}
 if(f.type==='consent'&&typeof value!=='boolean')throw new Error('قيمة الإقرار غير صحيحة.');if(f.type==='consent'&&required&&f.required&&value!==true)throw new Error('الإقرار «'+f.label+'» مطلوب.');
 if(f.type==='time'&&!/^\d{2}:\d{2}(?::\d{2})?$/.test(s))throw new Error('الوقت غير صحيح.');if(f.type==='datetime'&&!Number.isFinite(Date.parse(s)))throw new Error('التاريخ والوقت غير صحيحين.');
 if(f.type==='multiselect'){let a;try{a=JSON.parse(s);}catch{}if(!Array.isArray(a)||a.some(x=>!f.options.includes(x)))throw new Error('الاختيارات المتعددة غير صحيحة.');if(required&&f.required&&!a.length)throw new Error('اختر قيمة في «'+f.label+'».');}
 if(['radio','searchselect'].includes(f.type)&&!f.options.includes(s))throw new Error('اختر قيمة صحيحة في «'+f.label+'».');
 if(f.type==='table'){let a;try{a=JSON.parse(s);}catch{}if(!Array.isArray(a)||a.length>200||new Set(a.map(r=>r.id)).size!==a.length)throw new Error('صفوف الجدول غير صحيحة.');for(const r of a){if(!r||typeof r.id!=='string'||!r.cells||typeof r.cells!=='object')throw new Error('صف الجدول غير صحيح.');for(const c of f.columns??[]){const v=r.cells[c.id];if(required&&c.required&&(v===undefined||v===''))throw new Error('أكمل العمود «'+c.label+'».');if(v!==undefined&&typeof v!=='string'&&typeof v!=='boolean')throw new Error('قيمة الخلية غير صحيحة.');if(c.type==='number'&&v!==undefined&&v!==''&&!Number.isFinite(Number(v)))throw new Error('رقم الخلية غير صحيح.');}}}
}

export function protectValues(form:TestForm,group:'execution'|'preparation',values:Values,previous:Values){for(const f of form.fields.filter(f=>f.group===group&&(f.readOnly||f.disabled)&&!['calculated','user','file'].includes(f.type))){const expected=Object.hasOwn(previous,f.id)?previous[f.id]:f.defaultValue;if(Object.hasOwn(values,f.id)&&values[f.id]!==expected)throw new Error('الحقل «'+f.label+'» محمي من التعديل.');}}
