import type {TestForm,FormGroup} from './editor-model';
import type {Values} from './admin-model';
import {computedValues,effectiveField} from './advanced-model';
const encoder=new TextEncoder();
const xml=(s:unknown)=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'');
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
export function zip(parts:Record<string,string>):Uint8Array{
 const blocks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;
 for(const [path,source] of Object.entries(parts)){const name=encoder.encode(path),bytes=encoder.encode(source),crc=crc32(bytes),local=new Uint8Array(30+name.length+bytes.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);local.set(name,30);local.set(bytes,30+name.length);blocks.push(local);
 const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=local.length;}
 const size=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,central.length,true);ev.setUint16(10,central.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);const out=new Uint8Array(offset+size+22);let at=0;for(const b of [...blocks,...central,end]){out.set(b,at);at+=b.length;}return out;
}
export function exportedRows(form:TestForm,group:FormGroup,inputs:Values){const {values}=computedValues(form,inputs);return form.fields.filter(f=>f.group===group||f.group==='instructions').map(f=>effectiveField(f,values)).filter(f=>f.active&&f.printVisible!==false&&!['space','separator','file'].includes(f.type)).flatMap(f=>{
 const value=Object.hasOwn(values,f.id)?values[f.id]:f.defaultValue;
 if(f.type==='table'){let a:{id:string;cells:Record<string,string|boolean>}[]=[];try{a=JSON.parse(String(value)||'[]');}catch{}return [{label:f.label,value:''},...a.flatMap((r,i)=>(f.columns??[]).map(c=>({label:f.label+' / صف '+(i+1)+' / '+c.label,value:typeof r.cells?.[c.id]==='boolean'?r.cells[c.id]?'نعم':'لا':String(r.cells?.[c.id]??'')})))];}
 if(f.type==='multiselect'){let a:string[]=[];try{a=JSON.parse(String(value)||'[]');}catch{}return [{label:f.label,value:a.map(v=>f.optionItems?.find(o=>o.value===v)?.label??v).join('، ')}];}
 return [{label:f.label,value:typeof value==='boolean'?value?'نعم':'لا':f.optionItems?.find(o=>o.value===value)?.label??String(value)}];});}
export function createFormExport(form:TestForm,group:FormGroup,values:Values,format:'docx'|'xlsx'){
 const rows=exportedRows(form,group,values);const rel=(type:string,target:string)=>`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/${type}" Target="${target}"/></Relationships>`;
 if(format==='docx'){
 const paragraph=(text:string,bold=false)=>`<w:p><w:pPr><w:bidi/><w:jc w:val="right"/><w:spacing w:after="120"/></w:pPr><w:r><w:rPr><w:rtl/><w:rFonts w:ascii="Tajawal" w:hAnsi="Tajawal" w:cs="Tajawal"/>${bold?'<w:b/><w:bCs/>':''}<w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr><w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>`;
 return zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':rel('officeDocument','word/document.xml'),'word/document.xml':`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraph('نموذج اختبار ONYX · '+form.testId+' · الإصدار '+form.version,true)}${rows.map(r=>paragraph(r.label,true)+paragraph(r.value)).join('')}<w:sectPr><w:bidi/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="850" w:right="850" w:bottom="850" w:left="850"/></w:sectPr></w:body></w:document>`});}
 const sheetRows=[{label:'الحقل',value:'القيمة'},...rows];const cell=(value:string,ref:string)=>`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;
 return zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':rel('officeDocument','xl/workbook.xml'),'xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="نموذج الاختبار" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':rel('worksheet','worksheets/sheet1.xml'),'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><cols><col min="1" max="1" width="40" customWidth="1"/><col min="2" max="2" width="70" customWidth="1"/></cols><sheetData>${sheetRows.map((r,i)=>`<row r="${i+1}">${cell(r.label,'A'+(i+1))}${cell(r.value,'B'+(i+1))}</row>`).join('')}</sheetData></worksheet>`});
}
export function downloadForm(form:TestForm,group:FormGroup,values:Values,format:'docx'|'xlsx'){const bytes=createFormExport(form,group,values,format),blob=new Blob([new Uint8Array(bytes).buffer],{type:format==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ONYX-'+form.testId+'-V'+form.version+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
