import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const results=sqliteTable('results',{id:text('id').primaryKey(),formSnapshot:text('form_snapshot').notNull().default(''),runId:text('run_id').notNull().default(''),startedAt:text('started_at').notNull().default(''),approvedAt:text('approved_at').notNull().default(''),approvedBy:text('approved_by').notNull().default(''),status:text('status').notNull(),actual:text('actual').notNull(),notes:text('notes').notNull(),tester:text('tester').notNull(),testerId:text('tester_id').notNull().default(''),testerEmail:text('tester_email').notNull().default(''),evidenceUrl:text('evidence_url').notNull(),documentNumber:text('document_number').notNull().default(''),linkedDocumentNumber:text('linked_document_number').notNull().default(''),customValues:text('custom_values').notNull().default('{}'),version:integer('version').notNull(),updatedAt:text('updated_at').notNull()});
export const evidence=sqliteTable('evidence',{id:text('id').primaryKey(),testId:text('test_id').notNull(),runId:text('run_id').notNull().default(''),name:text('name').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_evidence_test_id').on(t.testId)]);
export const users=sqliteTable('app_users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),userId:text('user_id').unique(),name:text('name').notNull(),role:text('role').notNull(),permissions:text('permissions').notNull(),systems:text('systems').notNull(),active:integer('active').notNull(),version:integer('version').notNull(),updatedAt:text('updated_at').notNull()});
export const ownerIdentity=sqliteTable('site_owner',{id:text('id').primaryKey(),userId:text('user_id').notNull(),email:text('email').notNull(),name:text('name').notNull().default(''),createdAt:text('created_at').notNull()});
export const screenForms=sqliteTable('screen_forms',{screenId:text('screen_id').primaryKey(),fields:text('fields').notNull(),version:integer('version').notNull(),updatedAt:text('updated_at').notNull()});
export const testData=sqliteTable('test_data',{testId:text('test_id').primaryKey(),party:text('party').notNull(),amount:text('amount').notNull(),currency:text('currency').notNull(),documentNumber:text('document_number').notNull(),date:text('date').notNull(),branch:text('branch').notNull(),notes:text('notes').notNull(),customValues:text('custom_values').notNull(),ready:integer('ready').notNull(),version:integer('version').notNull(),updatedAt:text('updated_at').notNull()});

export const testForms=sqliteTable('test_forms',{testId:text('test_id').primaryKey(),screenId:text('screen_id').notNull(),fields:text('fields').notNull(),version:integer('version').notNull(),baseVersion:integer('base_version').notNull(),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull(),changeId:text('change_id').notNull()});
export const formVersions=sqliteTable('test_form_versions',{id:text('id').primaryKey(),testId:text('test_id').notNull(),version:integer('version').notNull(),snapshot:text('snapshot').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_test_form_versions_test_version').on(t.testId,t.version)]);

export const publishedForms=sqliteTable('published_forms',{testId:text('test_id').primaryKey(),version:integer('version').notNull(),snapshot:text('snapshot').notNull(),publishedAt:text('published_at').notNull(),actorId:text('actor_id').notNull()});

export const resultHistory=sqliteTable('result_history',{id:text('id').primaryKey(),testId:text('test_id').notNull(),snapshot:text('snapshot').notNull(),evidence:text('evidence').notNull(),actorId:text('actor_id').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_result_history_test').on(t.testId)]);
