import {db,checkOrigin,unavailable,checked,ApiError} from '../storage';
import {authorize,ownerEmail,ownerProfile,userRow,conflict} from '../auth';
import {validateUser} from '../../admin-model';
import type {AppUserRow,EmailRow} from '../types';
export async function GET(request:Request){try{await authorize(request,'manageUsers');const owner=await db().prepare("SELECT name FROM site_owner WHERE id='owner'").first<{name:string}>();const rows=await db().prepare('SELECT * FROM app_users ORDER BY name').all<AppUserRow>();return Response.json({users:[ownerProfile(ownerEmail(),owner?.name||ownerEmail()),...rows.results.map(userRow)]},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return unavailable(e);}}
export async function PUT(request:Request){const rejected=checkOrigin(request);if(rejected)return rejected;try{await authorize(request,'manageUsers');const body=await request.json();const value=checked(()=>validateUser(body,ownerEmail()));const now=new Date().toISOString();
 if(value.id){const existing=await db().prepare('SELECT email FROM app_users WHERE id=?').bind(value.id).first<EmailRow>();if(!existing)conflict();if(existing.email!==value.email)throw new ApiError('البريد هو هوية المستخدم ولا يتغير بعد الإنشاء. أوقف الحساب وأضف حساباً آخر.');}
 if(!value.id&&value.version!==0)conflict();const id=value.id||crypto.randomUUID();
 const row=await db().prepare('INSERT INTO app_users (id,email,name,role,permissions,systems,active,version,updated_at) SELECT ?,?,?,?,?,?,?,1,? WHERE ?=0 OR EXISTS (SELECT 1 FROM app_users WHERE id=?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,permissions=excluded.permissions,systems=excluded.systems,active=excluded.active,version=app_users.version+1,updated_at=excluded.updated_at WHERE app_users.version=? RETURNING *').bind(id,value.email,value.name,value.role,JSON.stringify(value.permissions),JSON.stringify(value.systems),value.active?1:0,now,value.version,id,value.version).first<AppUserRow>();if(!row)conflict();return Response.json({user:userRow(row)},{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){if(e instanceof Error&&e.message.includes('UNIQUE constraint'))return Response.json({error:'هذا البريد مسجل بالفعل.'},{status:409});return unavailable(e);}}
