import {db,checkOrigin,unavailable,checked,ApiError} from '../storage';
import {authorize,testSystem,getPublishedForm,getTestForm,formSelect,testFormRow,conflict} from '../auth';
import {validateTestForm} from '../../editor-model';
const headers={'Cache-Control':'private, no-store'};
export async function GET(request:Request){try{await authorize(request);const id=new URL(request.url).searchParams.get('testId')??'';await authorize(request,'view',testSystem(id));const editing=new URL(request.url).searchParams.get('mode')!=='published';if(editing)await authorize(request,'design',testSystem(id));const form=editing?await getTestForm(id):await getPublishedForm(id);const rows=editing?await db().prepare('SELECT version,created_at AS createdAt,actor_name AS actorName,snapshot FROM test_form_versions WHERE test_id=? ORDER BY version DESC LIMIT 20').bind(id).all<any>():{results:[]};return Response.json({form,revisions:rows.results.map(r=>({...r,snapshot:JSON.parse(r.snapshot)}))},{headers});}catch(e){return unavailable(e);}}
export async function PUT(request:Request){const rejected=checkOrigin(request);if(rejected)return rejected;try{
 await authorize(request,'design');const body=await request.json() as any;const value=checked(()=>validateTestForm(body));const user=await authorize(request,'design',testSystem(value.testId));const current=await getTestForm(value.testId);if(current.version!==value.version||current.baseVersion!==value.baseVersion)conflict();

 const records=await db().prepare('SELECT custom_values AS valuesJson FROM results WHERE id=? UNION ALL SELECT custom_values AS valuesJson FROM test_data WHERE test_id=?').bind(value.testId,value.testId).all<{valuesJson:string}>();
 for(const previous of current.fields){const next=value.fields.find(f=>f.id===previous.id);if(!next)continue;const used=records.results.some(r=>{const values=JSON.parse(r.valuesJson);return Object.hasOwn(values,previous.id)&&values[previous.id]!=='';});if(used&&previous.type!==next.type)throw new ApiError('الحقل «'+previous.label+'» يحتوي بيانات. انسخه بنوع جديد للحفاظ على البيانات السابقة.');if(used&&previous.type==='table'&&(previous.columns??[]).some(c=>!(next.columns??[]).some(n=>n.id===c.id&&n.type===c.type)))throw new ApiError('الجدول يحتوي بيانات؛ احتفظ بالأعمدة وأنواعها أو أنشئ نسخة جديدة.');}
 const now=new Date().toISOString(),changeId=crypto.randomUUID();const snapshot={...value,version:value.version+1,updatedAt:now,updatedBy:user.name,origin:'test'};
 const mutation=db().prepare('INSERT INTO test_forms (test_id,screen_id,fields,version,base_version,updated_at,updated_by,change_id) SELECT ?,?,?,1,?,?,?,? WHERE ?=0 OR EXISTS (SELECT 1 FROM test_forms WHERE test_id=?) ON CONFLICT(test_id) DO UPDATE SET fields=excluded.fields,version=test_forms.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by,change_id=excluded.change_id WHERE test_forms.version=? RETURNING '+formSelect).bind(value.testId,value.screenId,JSON.stringify(value.fields),value.baseVersion,now,user.name,changeId,value.version,value.testId,value.version);
 const audit=db().prepare('INSERT INTO test_form_versions (id,test_id,version,snapshot,actor_id,actor_name,created_at) SELECT ?,test_id,version,?,?,?,? FROM test_forms WHERE test_id=? AND change_id=?').bind(changeId,JSON.stringify(snapshot),user.identityId||user.id,user.name,now,value.testId,changeId);
 const [result]=await db().batch([mutation,audit]);if(!result.results.length)conflict();return Response.json({form:testFormRow(result.results[0])},{headers});
 }catch(e){return unavailable(e);}}
